/* A recursive-descent parser generated by peg 0.1.2 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 32


#include "ruby.h"
RUBY_GLOBAL_SETUP;

FILE *source_file;

int yy_input(char *buf, int max_size);

#define YY_INPUT(b, r, ms) (r = yy_input(b, ms))

#define YYSTYPE volatile VALUE

#define SET_HASH_KEY(hash, key, val) \
  rb_hash_aset(hash, ID2SYM(rb_intern(key)), val);

#define SAVE_HASH(ref, key, val) \
  ref = rb_hash_new();           \
  SET_HASH_KEY(ref, key, val);   \
  K(ref);

#define K(val) rb_ary_push(__keep__, val)

VALUE body; /* ruby array */
VALUE stack; /* ruby array */
VALUE __keep__; /* ruby array to avoid GC of our objects */

#define SPUSH() \
  rb_ary_push(stack, rb_ary_new())

#define SADD(val) \
  rb_ary_push(rb_ary_entry(stack, RARRAY_LEN(stack) - 1), val)

#define SPOP() \
  rb_ary_pop(stack)



#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      yybuflen *= 2;
      yybuf= realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if (yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yybuf+yypos));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yybuf+yypos));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end)
{
  while (yythunkpos >= yythunkslen)
    {
      yythunkslen *= 2;
      yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng - 1))
	{
	  yytextlen *= 2;
	  yytext= realloc(yytext, yytextlen);
	}
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_digit(); /* 32 */
YY_RULE(int) yy_esc(); /* 31 */
YY_RULE(int) yy_nsq(); /* 30 */
YY_RULE(int) yy_ndq(); /* 29 */
YY_RULE(int) yy_sq(); /* 28 */
YY_RULE(int) yy_dq(); /* 27 */
YY_RULE(int) yy_rangeop(); /* 26 */
YY_RULE(int) yy_integer(); /* 25 */
YY_RULE(int) yy_range(); /* 24 */
YY_RULE(int) yy_string(); /* 23 */
YY_RULE(int) yy_operand(); /* 22 */
YY_RULE(int) yy_func_args(); /* 21 */
YY_RULE(int) yy_atom(); /* 20 */
YY_RULE(int) yy_list(); /* 19 */
YY_RULE(int) yy_func(); /* 18 */
YY_RULE(int) yy_eop(); /* 17 */
YY_RULE(int) yy_op(); /* 16 */
YY_RULE(int) yy_ecall(); /* 15 */
YY_RULE(int) yy_arg_sep(); /* 14 */
YY_RULE(int) yy_symbol(); /* 13 */
YY_RULE(int) yy_identifier(); /* 12 */
YY_RULE(int) yy___(); /* 11 */
YY_RULE(int) yy_expr(); /* 10 */
YY_RULE(int) yy_assign(); /* 9 */
YY_RULE(int) yy_icall(); /* 8 */
YY_RULE(int) yy_comment(); /* 7 */
YY_RULE(int) yy_empty_line(); /* 6 */
YY_RULE(int) yy__(); /* 5 */
YY_RULE(int) yy_bad(); /* 4 */
YY_RULE(int) yy_eof(); /* 3 */
YY_RULE(int) yy_lexpr(); /* 2 */
YY_RULE(int) yy_body(); /* 1 */

YY_ACTION(void) yy_1_integer(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_integer\n"));
   K(yy = rb_str_new(yytext, yyleng)); ;
}
YY_ACTION(void) yy_1_identifier(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_identifier\n"));
   K(yy = rb_str_new(yytext, yyleng)); ;
}
YY_ACTION(void) yy_2_symbol(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_symbol\n"));
   K(yy = rb_str_new(yytext, yyleng)); ;
}
YY_ACTION(void) yy_1_symbol(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_symbol\n"));
   K(yy = rb_str_new(yytext, yyleng)); ;
}
YY_ACTION(void) yy_1_comment(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_comment\n"));
   yy = 0; ;
}
YY_ACTION(void) yy_1_empty_line(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_empty_line\n"));
   yy = 0; ;
}
YY_ACTION(void) yy_2_string(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_string\n"));
   K(yy = rb_str_new(yytext, yyleng)); ;
}
YY_ACTION(void) yy_1_string(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_string\n"));
   K(yy = rb_str_new(yytext, yyleng)); ;
}
YY_ACTION(void) yy_1_range(char *yytext, int yyleng)
{
#define last yyval[-1]
#define first yyval[-2]
  yyprintf((stderr, "do yy_1_range\n"));
   VALUE rng = rb_hash_new();
                                                     SET_HASH_KEY(rng, "first", first);
                                                     SET_HASH_KEY(rng, "last", last);
                                                     K(yy = rng); ;
#undef last
#undef first
}
YY_ACTION(void) yy_2_rangeop(char *yytext, int yyleng)
{
#define int yyval[-1]
#define var yyval[-2]
  yyprintf((stderr, "do yy_2_rangeop\n"));
   SAVE_HASH(yy, "integer", int); ;
#undef int
#undef var
}
YY_ACTION(void) yy_1_rangeop(char *yytext, int yyleng)
{
#define int yyval[-1]
#define var yyval[-2]
  yyprintf((stderr, "do yy_1_rangeop\n"));
   SAVE_HASH(yy, "var", var); ;
#undef int
#undef var
}
YY_ACTION(void) yy_3_list(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_3_list\n"));
   SAVE_HASH(yy, "list", SPOP()); ;
#undef e
}
YY_ACTION(void) yy_2_list(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_2_list\n"));
   SADD(e); ;
#undef e
}
YY_ACTION(void) yy_1_list(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_1_list\n"));
   SPUSH(); ;
#undef e
}
YY_ACTION(void) yy_4_atom(char *yytext, int yyleng)
{
#define int yyval[-1]
#define rng yyval[-2]
#define str yyval[-3]
#define var yyval[-4]
  yyprintf((stderr, "do yy_4_atom\n"));
   SAVE_HASH(yy, "integer", int); ;
#undef int
#undef rng
#undef str
#undef var
}
YY_ACTION(void) yy_3_atom(char *yytext, int yyleng)
{
#define int yyval[-1]
#define rng yyval[-2]
#define str yyval[-3]
#define var yyval[-4]
  yyprintf((stderr, "do yy_3_atom\n"));
   SAVE_HASH(yy, "range", rng); ;
#undef int
#undef rng
#undef str
#undef var
}
YY_ACTION(void) yy_2_atom(char *yytext, int yyleng)
{
#define int yyval[-1]
#define rng yyval[-2]
#define str yyval[-3]
#define var yyval[-4]
  yyprintf((stderr, "do yy_2_atom\n"));
   SAVE_HASH(yy, "string", str); ;
#undef int
#undef rng
#undef str
#undef var
}
YY_ACTION(void) yy_1_atom(char *yytext, int yyleng)
{
#define int yyval[-1]
#define rng yyval[-2]
#define str yyval[-3]
#define var yyval[-4]
  yyprintf((stderr, "do yy_1_atom\n"));
   SAVE_HASH(yy, "var", var); ;
#undef int
#undef rng
#undef str
#undef var
}
YY_ACTION(void) yy_1_op(char *yytext, int yyleng)
{
#define right yyval[-1]
#define symbol yyval[-2]
#define left yyval[-3]
  yyprintf((stderr, "do yy_1_op\n"));
   VALUE op = rb_hash_new();
                                                     SET_HASH_KEY(op, "left", left);
                                                     SET_HASH_KEY(op, "symbol", symbol);
                                                     SET_HASH_KEY(op, "right", right);
                                                     SAVE_HASH(yy, "op", op); ;
#undef right
#undef symbol
#undef left
}
YY_ACTION(void) yy_4_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_4_func_args\n"));
   yy = 0; ;
#undef arg
}
YY_ACTION(void) yy_3_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_3_func_args\n"));
   K(yy = SPOP()); ;
#undef arg
}
YY_ACTION(void) yy_2_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_2_func_args\n"));
   VALUE a = rb_hash_new();
                                                     SET_HASH_KEY(a, "arg", arg);
                                                     SADD(a); ;
#undef arg
}
YY_ACTION(void) yy_1_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_1_func_args\n"));
   SPUSH(); ;
#undef arg
}
YY_ACTION(void) yy_3_func(char *yytext, int yyleng)
{
#define e yyval[-1]
#define args yyval[-2]
  yyprintf((stderr, "do yy_3_func\n"));
   VALUE func = rb_hash_new();
                                                     args && SET_HASH_KEY(func, "args", args);
                                                     SET_HASH_KEY(func, "body", SPOP());
                                                     SAVE_HASH(yy, "func", func); ;
#undef e
#undef args
}
YY_ACTION(void) yy_2_func(char *yytext, int yyleng)
{
#define e yyval[-1]
#define args yyval[-2]
  yyprintf((stderr, "do yy_2_func\n"));
   e && SADD(e); ;
#undef e
#undef args
}
YY_ACTION(void) yy_1_func(char *yytext, int yyleng)
{
#define e yyval[-1]
#define args yyval[-2]
  yyprintf((stderr, "do yy_1_func\n"));
   SPUSH(); ;
#undef e
#undef args
}
YY_ACTION(void) yy_3_ecall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_3_ecall\n"));
   VALUE call = rb_hash_new();
                                                     SET_HASH_KEY(call, "name", name);
                                                     SET_HASH_KEY(call, "args", SPOP());
                                                     SAVE_HASH(yy, "call", call); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_2_ecall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_2_ecall\n"));
   SADD(arg); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_1_ecall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_1_ecall\n"));
   SPUSH(); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_3_icall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_3_icall\n"));
   VALUE call = rb_hash_new();
                                                     SET_HASH_KEY(call, "name", name);
                                                     SET_HASH_KEY(call, "args", SPOP());
                                                     SAVE_HASH(yy, "call", call); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_2_icall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_2_icall\n"));
   SADD(arg); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_1_icall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_1_icall\n"));
   SPUSH(); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_1_assign(char *yytext, int yyleng)
{
#define val yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_1_assign\n"));
   VALUE assign = rb_hash_new();
                                                     SET_HASH_KEY(assign, "name", name);
                                                     SET_HASH_KEY(assign, "val", val);
                                                     SAVE_HASH(yy, "assign", assign); ;
#undef val
#undef name
}
YY_ACTION(void) yy_1_bad(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bad\n"));
   VALUE error = rb_hash_new();
                                                     SET_HASH_KEY(error, "type", rb_str_new2("syntax"));
                                                     SET_HASH_KEY(error, "expr", rb_str_new(yytext, yyleng));
                                                     VALUE e = rb_hash_new();
                                                     SET_HASH_KEY(e, "error", error); rb_ary_push(body, e); ;
}
YY_ACTION(void) yy_1_body(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_1_body\n"));
   e && rb_ary_push(body, e); ;
#undef e
}

YY_RULE(int) yy_digit()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "digit"));  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "digit", yybuf+yypos));
  return 1;
  l1:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "digit", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_esc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "esc"));  if (!yymatchChar('\\')) goto l2;  if (!yymatchDot()) goto l2;
  yyprintf((stderr, "  ok   %s @ %s\n", "esc", yybuf+yypos));
  return 1;
  l2:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "esc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_nsq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "nsq"));
  {  int yypos4= yypos, yythunkpos4= yythunkpos;  if (!yy_sq()) goto l4;  goto l3;
  l4:;	  yypos= yypos4; yythunkpos= yythunkpos4;
  }  if (!yymatchDot()) goto l3;
  yyprintf((stderr, "  ok   %s @ %s\n", "nsq", yybuf+yypos));
  return 1;
  l3:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "nsq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ndq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "ndq"));
  {  int yypos6= yypos, yythunkpos6= yythunkpos;  if (!yy_dq()) goto l6;  goto l5;
  l6:;	  yypos= yypos6; yythunkpos= yythunkpos6;
  }  if (!yymatchDot()) goto l5;
  yyprintf((stderr, "  ok   %s @ %s\n", "ndq", yybuf+yypos));
  return 1;
  l5:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ndq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_sq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "sq"));  if (!yymatchChar('\'')) goto l7;
  yyprintf((stderr, "  ok   %s @ %s\n", "sq", yybuf+yypos));
  return 1;
  l7:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_dq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "dq"));  if (!yymatchChar('\"')) goto l8;
  yyprintf((stderr, "  ok   %s @ %s\n", "dq", yybuf+yypos));
  return 1;
  l8:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "dq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_rangeop()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "rangeop"));
  {  int yypos10= yypos, yythunkpos10= yythunkpos;  if (!yy_identifier()) goto l11;  yyDo(yySet, -2, 0);  yyDo(yy_1_rangeop, yybegin, yyend);  goto l10;
  l11:;	  yypos= yypos10; yythunkpos= yythunkpos10;  if (!yy_integer()) goto l12;  yyDo(yySet, -1, 0);  yyDo(yy_2_rangeop, yybegin, yyend);  goto l10;
  l12:;	  yypos= yypos10; yythunkpos= yythunkpos10;  if (!yy_eop()) goto l13;  goto l10;
  l13:;	  yypos= yypos10; yythunkpos= yythunkpos10;  if (!yy_ecall()) goto l9;
  }
  l10:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "rangeop", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l9:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "rangeop", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_integer()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "integer"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l14;  if (!yy_digit()) goto l14;
  l15:;	
  {  int yypos16= yypos, yythunkpos16= yythunkpos;  if (!yy_digit()) goto l16;  goto l15;
  l16:;	  yypos= yypos16; yythunkpos= yythunkpos16;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l14;  yyDo(yy_1_integer, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "integer", yybuf+yypos));
  return 1;
  l14:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "integer", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_range()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "range"));  if (!yy_rangeop()) goto l17;  yyDo(yySet, -2, 0);  if (!yymatchString("..")) goto l17;  if (!yy_rangeop()) goto l17;  yyDo(yySet, -1, 0);  yyDo(yy_1_range, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "range", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l17:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "range", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_string()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "string"));
  {  int yypos19= yypos, yythunkpos19= yythunkpos;  if (!yy_dq()) goto l20;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l20;
  l21:;	
  {  int yypos22= yypos, yythunkpos22= yythunkpos;
  {  int yypos23= yypos, yythunkpos23= yythunkpos;  if (!yy_esc()) goto l24;  goto l23;
  l24:;	  yypos= yypos23; yythunkpos= yythunkpos23;  if (!yy_ndq()) goto l22;
  }
  l23:;	  goto l21;
  l22:;	  yypos= yypos22; yythunkpos= yythunkpos22;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l20;  if (!yy_dq()) goto l20;  yyDo(yy_1_string, yybegin, yyend);  goto l19;
  l20:;	  yypos= yypos19; yythunkpos= yythunkpos19;  if (!yy_sq()) goto l18;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l18;
  l25:;	
  {  int yypos26= yypos, yythunkpos26= yythunkpos;
  {  int yypos27= yypos, yythunkpos27= yythunkpos;  if (!yy_esc()) goto l28;  goto l27;
  l28:;	  yypos= yypos27; yythunkpos= yythunkpos27;  if (!yy_nsq()) goto l26;
  }
  l27:;	  goto l25;
  l26:;	  yypos= yypos26; yythunkpos= yythunkpos26;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l18;  if (!yy_sq()) goto l18;  yyDo(yy_2_string, yybegin, yyend);
  }
  l19:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "string", yybuf+yypos));
  return 1;
  l18:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "string", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_operand()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "operand"));
  {  int yypos30= yypos, yythunkpos30= yythunkpos;  if (!yy_list()) goto l31;  goto l30;
  l31:;	  yypos= yypos30; yythunkpos= yythunkpos30;  if (!yy_atom()) goto l32;  goto l30;
  l32:;	  yypos= yypos30; yythunkpos= yythunkpos30;  if (!yy_eop()) goto l33;  goto l30;
  l33:;	  yypos= yypos30; yythunkpos= yythunkpos30;  if (!yy_ecall()) goto l29;
  }
  l30:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "operand", yybuf+yypos));
  return 1;
  l29:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "operand", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_func_args()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "func_args"));
  {  int yypos35= yypos, yythunkpos35= yythunkpos;  if (!yymatchChar('[')) goto l36;  yyDo(yy_1_func_args, yybegin, yyend);
  l39:;	
  {  int yypos40= yypos, yythunkpos40= yythunkpos;  if (!yy__()) goto l40;  goto l39;
  l40:;	  yypos= yypos40; yythunkpos= yythunkpos40;
  }  if (!yy_identifier()) goto l36;  yyDo(yySet, -1, 0);  yyDo(yy_2_func_args, yybegin, yyend);
  l37:;	
  {  int yypos38= yypos, yythunkpos38= yythunkpos;
  l41:;	
  {  int yypos42= yypos, yythunkpos42= yythunkpos;  if (!yy__()) goto l42;  goto l41;
  l42:;	  yypos= yypos42; yythunkpos= yythunkpos42;
  }  if (!yy_identifier()) goto l38;  yyDo(yySet, -1, 0);  yyDo(yy_2_func_args, yybegin, yyend);  goto l37;
  l38:;	  yypos= yypos38; yythunkpos= yythunkpos38;
  }
  l43:;	
  {  int yypos44= yypos, yythunkpos44= yythunkpos;  if (!yy__()) goto l44;  goto l43;
  l44:;	  yypos= yypos44; yythunkpos= yythunkpos44;
  }  if (!yymatchChar(']')) goto l36;
  l45:;	
  {  int yypos46= yypos, yythunkpos46= yythunkpos;  if (!yy__()) goto l46;  goto l45;
  l46:;	  yypos= yypos46; yythunkpos= yythunkpos46;
  }  yyDo(yy_3_func_args, yybegin, yyend);  goto l35;
  l36:;	  yypos= yypos35; yythunkpos= yythunkpos35;
  {  int yypos47= yypos, yythunkpos47= yythunkpos;  if (!yymatchChar('{')) goto l34;  yypos= yypos47; yythunkpos= yythunkpos47;
  }  yyDo(yy_4_func_args, yybegin, yyend);
  }
  l35:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "func_args", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l34:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "func_args", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_atom()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 4, 0);
  yyprintf((stderr, "%s\n", "atom"));
  {  int yypos49= yypos, yythunkpos49= yythunkpos;  if (!yy_identifier()) goto l50;  yyDo(yySet, -4, 0);  yyDo(yy_1_atom, yybegin, yyend);  goto l49;
  l50:;	  yypos= yypos49; yythunkpos= yythunkpos49;  if (!yy_string()) goto l51;  yyDo(yySet, -3, 0);  yyDo(yy_2_atom, yybegin, yyend);  goto l49;
  l51:;	  yypos= yypos49; yythunkpos= yythunkpos49;  if (!yy_range()) goto l52;  yyDo(yySet, -2, 0);  yyDo(yy_3_atom, yybegin, yyend);  goto l49;
  l52:;	  yypos= yypos49; yythunkpos= yythunkpos49;  if (!yy_integer()) goto l48;  yyDo(yySet, -1, 0);  yyDo(yy_4_atom, yybegin, yyend);
  }
  l49:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "atom", yybuf+yypos));  yyDo(yyPop, 4, 0);
  return 1;
  l48:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "atom", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "list"));  if (!yymatchChar('[')) goto l53;
  l54:;	
  {  int yypos55= yypos, yythunkpos55= yythunkpos;  if (!yy__()) goto l55;  goto l54;
  l55:;	  yypos= yypos55; yythunkpos= yythunkpos55;
  }  yyDo(yy_1_list, yybegin, yyend);
  l56:;	
  {  int yypos57= yypos, yythunkpos57= yythunkpos;  if (!yy_expr()) goto l57;  yyDo(yySet, -1, 0);
  l58:;	
  {  int yypos59= yypos, yythunkpos59= yythunkpos;
  {  int yypos60= yypos, yythunkpos60= yythunkpos;  if (!yy__()) goto l61;  goto l60;
  l61:;	  yypos= yypos60; yythunkpos= yythunkpos60;  if (!yy___()) goto l59;
  }
  l60:;	  goto l58;
  l59:;	  yypos= yypos59; yythunkpos= yythunkpos59;
  }  yyDo(yy_2_list, yybegin, yyend);  goto l56;
  l57:;	  yypos= yypos57; yythunkpos= yythunkpos57;
  }  if (!yymatchChar(']')) goto l53;  yyDo(yy_3_list, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "list", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l53:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "list", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_func()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "func"));  if (!yy_func_args()) goto l62;  yyDo(yySet, -2, 0);  if (!yymatchChar('{')) goto l62;
  l63:;	
  {  int yypos64= yypos, yythunkpos64= yythunkpos;
  {  int yypos65= yypos, yythunkpos65= yythunkpos;  if (!yy__()) goto l66;  goto l65;
  l66:;	  yypos= yypos65; yythunkpos= yythunkpos65;  if (!yy___()) goto l64;
  }
  l65:;	  goto l63;
  l64:;	  yypos= yypos64; yythunkpos= yythunkpos64;
  }  yyDo(yy_1_func, yybegin, yyend);  if (!yy_lexpr()) goto l62;  yyDo(yySet, -1, 0);  yyDo(yy_2_func, yybegin, yyend);
  l67:;	
  {  int yypos68= yypos, yythunkpos68= yythunkpos;  if (!yy_lexpr()) goto l68;  yyDo(yySet, -1, 0);  yyDo(yy_2_func, yybegin, yyend);  goto l67;
  l68:;	  yypos= yypos68; yythunkpos= yythunkpos68;
  }
  l69:;	
  {  int yypos70= yypos, yythunkpos70= yythunkpos;  if (!yy__()) goto l70;  goto l69;
  l70:;	  yypos= yypos70; yythunkpos= yythunkpos70;
  }  if (!yymatchChar('}')) goto l62;  yyDo(yy_3_func, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "func", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l62:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "func", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eop()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eop"));  if (!yymatchChar('(')) goto l71;  if (!yy_op()) goto l71;  if (!yymatchChar(')')) goto l71;
  yyprintf((stderr, "  ok   %s @ %s\n", "eop", yybuf+yypos));
  return 1;
  l71:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eop", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_op()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "op"));  if (!yy_operand()) goto l72;  yyDo(yySet, -3, 0);  if (!yy__()) goto l72;
  l73:;	
  {  int yypos74= yypos, yythunkpos74= yythunkpos;  if (!yy__()) goto l74;  goto l73;
  l74:;	  yypos= yypos74; yythunkpos= yythunkpos74;
  }  if (!yy_symbol()) goto l72;  yyDo(yySet, -2, 0);  if (!yy__()) goto l72;
  l75:;	
  {  int yypos76= yypos, yythunkpos76= yythunkpos;  if (!yy__()) goto l76;  goto l75;
  l76:;	  yypos= yypos76; yythunkpos= yythunkpos76;
  }  if (!yy_operand()) goto l72;  yyDo(yySet, -1, 0);  yyDo(yy_1_op, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "op", yybuf+yypos));  yyDo(yyPop, 3, 0);
  return 1;
  l72:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "op", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ecall()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "ecall"));  if (!yymatchChar('(')) goto l77;  if (!yy_identifier()) goto l77;  yyDo(yySet, -2, 0);  yyDo(yy_1_ecall, yybegin, yyend);
  l78:;	
  {  int yypos79= yypos, yythunkpos79= yythunkpos;  if (!yy_arg_sep()) goto l79;  if (!yy_expr()) goto l79;  yyDo(yySet, -1, 0);  yyDo(yy_2_ecall, yybegin, yyend);  goto l78;
  l79:;	  yypos= yypos79; yythunkpos= yythunkpos79;
  }  if (!yymatchChar(')')) goto l77;  yyDo(yy_3_ecall, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "ecall", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l77:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ecall", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_arg_sep()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "arg_sep"));
  {  int yypos81= yypos, yythunkpos81= yythunkpos;  if (!yymatchChar(',')) goto l82;
  l83:;	
  {  int yypos84= yypos, yythunkpos84= yythunkpos;
  {  int yypos85= yypos, yythunkpos85= yythunkpos;  if (!yy__()) goto l86;  goto l85;
  l86:;	  yypos= yypos85; yythunkpos= yythunkpos85;  if (!yy___()) goto l84;
  }
  l85:;	  goto l83;
  l84:;	  yypos= yypos84; yythunkpos= yythunkpos84;
  }  goto l81;
  l82:;	  yypos= yypos81; yythunkpos= yythunkpos81;  if (!yy__()) goto l80;
  l87:;	
  {  int yypos88= yypos, yythunkpos88= yythunkpos;  if (!yy__()) goto l88;  goto l87;
  l88:;	  yypos= yypos88; yythunkpos= yythunkpos88;
  }
  }
  l81:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "arg_sep", yybuf+yypos));
  return 1;
  l80:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "arg_sep", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_symbol()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "symbol"));
  {  int yypos90= yypos, yythunkpos90= yythunkpos;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l91;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\320\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l91;
  l92:;	
  {  int yypos93= yypos, yythunkpos93= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\320\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l93;  goto l92;
  l93:;	  yypos= yypos93; yythunkpos= yythunkpos93;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l91;  yyDo(yy_1_symbol, yybegin, yyend);  goto l90;
  l91:;	  yypos= yypos90; yythunkpos= yythunkpos90;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l89;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\360\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l89;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\360\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l89;
  l94:;	
  {  int yypos95= yypos, yythunkpos95= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\360\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l95;  goto l94;
  l95:;	  yypos= yypos95; yythunkpos= yythunkpos95;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l89;  yyDo(yy_2_symbol, yybegin, yyend);
  }
  l90:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "symbol", yybuf+yypos));
  return 1;
  l89:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "symbol", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_identifier()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "identifier"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l96;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l96;
  l97:;	
  {  int yypos98= yypos, yythunkpos98= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\040\377\003\000\000\000\000\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l98;  goto l97;
  l98:;	  yypos= yypos98; yythunkpos= yythunkpos98;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l96;  yyDo(yy_1_identifier, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "identifier", yybuf+yypos));
  return 1;
  l96:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "identifier", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy___()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "__"));
  {  int yypos100= yypos, yythunkpos100= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l100;  goto l101;
  l100:;	  yypos= yypos100; yythunkpos= yythunkpos100;
  }
  l101:;	  if (!yymatchClass((unsigned char *)"\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l99;
  yyprintf((stderr, "  ok   %s @ %s\n", "__", yybuf+yypos));
  return 1;
  l99:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "__", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_expr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "expr"));
  {  int yypos103= yypos, yythunkpos103= yythunkpos;  if (!yy_op()) goto l104;  goto l103;
  l104:;	  yypos= yypos103; yythunkpos= yythunkpos103;  if (!yy_eop()) goto l105;  goto l103;
  l105:;	  yypos= yypos103; yythunkpos= yythunkpos103;  if (!yy_ecall()) goto l106;  goto l103;
  l106:;	  yypos= yypos103; yythunkpos= yythunkpos103;  if (!yy_func()) goto l107;  goto l103;
  l107:;	  yypos= yypos103; yythunkpos= yythunkpos103;  if (!yy_list()) goto l108;  goto l103;
  l108:;	  yypos= yypos103; yythunkpos= yythunkpos103;  if (!yy_atom()) goto l102;
  }
  l103:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "expr", yybuf+yypos));
  return 1;
  l102:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "expr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_assign()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "assign"));
  {  int yypos110= yypos, yythunkpos110= yythunkpos;  if (!yy_identifier()) goto l111;  yyDo(yySet, -2, 0);  goto l110;
  l111:;	  yypos= yypos110; yythunkpos= yythunkpos110;  if (!yy_symbol()) goto l109;  yyDo(yySet, -2, 0);
  }
  l110:;	  if (!yy__()) goto l109;
  l112:;	
  {  int yypos113= yypos, yythunkpos113= yythunkpos;  if (!yy__()) goto l113;  goto l112;
  l113:;	  yypos= yypos113; yythunkpos= yythunkpos113;
  }  if (!yymatchChar('=')) goto l109;  if (!yy__()) goto l109;
  l114:;	
  {  int yypos115= yypos, yythunkpos115= yythunkpos;  if (!yy__()) goto l115;  goto l114;
  l115:;	  yypos= yypos115; yythunkpos= yythunkpos115;
  }
  {  int yypos116= yypos, yythunkpos116= yythunkpos;  if (!yy_icall()) goto l117;  yyDo(yySet, -1, 0);  goto l116;
  l117:;	  yypos= yypos116; yythunkpos= yythunkpos116;  if (!yy_expr()) goto l109;  yyDo(yySet, -1, 0);
  }
  l116:;	  yyDo(yy_1_assign, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "assign", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l109:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "assign", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_icall()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "icall"));  if (!yy_identifier()) goto l118;  yyDo(yySet, -2, 0);  yyDo(yy_1_icall, yybegin, yyend);  if (!yy_arg_sep()) goto l118;  if (!yy_expr()) goto l118;  yyDo(yySet, -1, 0);  yyDo(yy_2_icall, yybegin, yyend);
  l119:;	
  {  int yypos120= yypos, yythunkpos120= yythunkpos;  if (!yy_arg_sep()) goto l120;  if (!yy_expr()) goto l120;  yyDo(yySet, -1, 0);  yyDo(yy_2_icall, yybegin, yyend);  goto l119;
  l120:;	  yypos= yypos120; yythunkpos= yythunkpos120;
  }  yyDo(yy_3_icall, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "icall", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l118:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "icall", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_comment()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "comment"));
  l122:;	
  {  int yypos123= yypos, yythunkpos123= yythunkpos;  if (!yy__()) goto l123;  goto l122;
  l123:;	  yypos= yypos123; yythunkpos= yythunkpos123;
  }  if (!yymatchChar('#')) goto l121;
  l124:;	
  {  int yypos125= yypos, yythunkpos125= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\333\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l125;  goto l124;
  l125:;	  yypos= yypos125; yythunkpos= yythunkpos125;
  }
  {  int yypos126= yypos, yythunkpos126= yythunkpos;  if (!yy___()) goto l126;  goto l127;
  l126:;	  yypos= yypos126; yythunkpos= yythunkpos126;
  }
  l127:;	  yyDo(yy_1_comment, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "comment", yybuf+yypos));
  return 1;
  l121:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "comment", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_empty_line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "empty_line"));
  l129:;	
  {  int yypos130= yypos, yythunkpos130= yythunkpos;  if (!yy__()) goto l130;  goto l129;
  l130:;	  yypos= yypos130; yythunkpos= yythunkpos130;
  }  if (!yy___()) goto l128;  yyDo(yy_1_empty_line, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "empty_line", yybuf+yypos));
  return 1;
  l128:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "empty_line", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy__()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "_"));  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l131;
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yybuf+yypos));
  return 1;
  l131:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "_", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bad()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bad"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l132;  if (!yymatchDot()) goto l132;
  l133:;	
  {  int yypos134= yypos, yythunkpos134= yythunkpos;  if (!yymatchDot()) goto l134;  goto l133;
  l134:;	  yypos= yypos134; yythunkpos= yythunkpos134;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l132;  yyDo(yy_1_bad, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bad", yybuf+yypos));
  return 1;
  l132:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bad", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eof()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eof"));
  {  int yypos136= yypos, yythunkpos136= yythunkpos;  if (!yymatchDot()) goto l136;  goto l135;
  l136:;	  yypos= yypos136; yythunkpos= yythunkpos136;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "eof", yybuf+yypos));
  return 1;
  l135:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eof", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_lexpr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "lexpr"));
  l138:;	
  {  int yypos139= yypos, yythunkpos139= yythunkpos;  if (!yy__()) goto l139;  goto l138;
  l139:;	  yypos= yypos139; yythunkpos= yythunkpos139;
  }
  {  int yypos140= yypos, yythunkpos140= yythunkpos;  if (!yy_empty_line()) goto l141;  goto l140;
  l141:;	  yypos= yypos140; yythunkpos= yythunkpos140;  if (!yy_comment()) goto l142;  goto l140;
  l142:;	  yypos= yypos140; yythunkpos= yythunkpos140;  if (!yy_icall()) goto l143;  goto l140;
  l143:;	  yypos= yypos140; yythunkpos= yythunkpos140;  if (!yy_assign()) goto l144;  goto l140;
  l144:;	  yypos= yypos140; yythunkpos= yythunkpos140;  if (!yy_expr()) goto l137;
  }
  l140:;	
  l145:;	
  {  int yypos146= yypos, yythunkpos146= yythunkpos;  if (!yy__()) goto l146;  goto l145;
  l146:;	  yypos= yypos146; yythunkpos= yythunkpos146;
  }
  {  int yypos147= yypos, yythunkpos147= yythunkpos;  if (!yy___()) goto l147;  goto l148;
  l147:;	  yypos= yypos147; yythunkpos= yythunkpos147;
  }
  l148:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "lexpr", yybuf+yypos));
  return 1;
  l137:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "lexpr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_body()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "body"));
  {  int yypos150= yypos, yythunkpos150= yythunkpos;  if (!yy_lexpr()) goto l151;  yyDo(yySet, -1, 0);  yyDo(yy_1_body, yybegin, yyend);
  l152:;	
  {  int yypos153= yypos, yythunkpos153= yythunkpos;  if (!yy_lexpr()) goto l153;  yyDo(yySet, -1, 0);  yyDo(yy_1_body, yybegin, yyend);  goto l152;
  l153:;	  yypos= yypos153; yythunkpos= yythunkpos153;
  }  if (!yy_eof()) goto l151;  goto l150;
  l151:;	  yypos= yypos150; yythunkpos= yythunkpos150;
  l154:;	
  {  int yypos155= yypos, yythunkpos155= yythunkpos;  if (!yy_lexpr()) goto l155;  goto l154;
  l155:;	  yypos= yypos155; yythunkpos= yythunkpos155;
  }  if (!yy_bad()) goto l149;  if (!yy_eof()) goto l149;
  }
  l150:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "body", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l149:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "body", yybuf+yypos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= malloc(yybuflen);
      yytextlen= 1024;
      yytext= malloc(yytextlen);
      yythunkslen= 32;
      yythunks= malloc(sizeof(yythunk) * yythunkslen);
      yyvalslen= 32;
      yyvals= malloc(sizeof(YYSTYPE) * yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_body);
}

#endif


/* borrowed from O'Reilly book "lex & yacc" pg. 157 */
char *yy_input_ptr;
int yy_input_len;

int yy_input(char *buf, int max_size) {
  int len = strlen(yy_input_ptr);
  int n = max_size < len ? max_size : len;
  if(n > 0) {
    memcpy(buf, yy_input_ptr, n);
    yy_input_ptr += n;
  }
  return n;
}

static VALUE Parser_parse(VALUE self, VALUE source) {
  yy_input_ptr = rb_string_value_cstr(&source);
  yy_input_len = strlen(yy_input_ptr);
  body = rb_ary_new();
  stack = rb_ary_new();
  while (yyparse());
  rb_gc_register_address(&body);
  rb_funcall(__keep__, rb_intern("clear"), 0, 0);
  return body;
}

void Init_parser() {
  rb_gc_register_address(&body);
  VALUE Airball = rb_define_module("Airball");
  VALUE Parser = rb_define_class_under(Airball, "Parser", rb_cObject);
  rb_define_const(Parser, "IMPLEMENTATION", rb_str_new2("c"));
  rb_define_method(Parser, "parse", Parser_parse, 1);
  __keep__ = rb_ary_new();
  rb_gc_register_address(&__keep__);
  rb_gc_register_address(&stack);
}


/* borrowed from why's shoes/world.c
   works with ruby 1.9 only */
/* not used
int init_ruby() {
  VALUE v;
  char *argv[] = {"ruby", "-e", "1"};
  RUBY_INIT_STACK;
  ruby_init();
  v = (VALUE)ruby_options(3, argv);
  return !FIXNUM_P(v);
}
*/

/* not used
void parse(char *filename) {
  source_file = fopen(filename, "r");
  body = rb_ary_new();
  while (yyparse());
  fclose(source_file);
}
*/

/* not used
VALUE build_program(VALUE *body) {
  VALUE Airball = rb_const_get(rb_cObject, rb_intern("Airball"));
  VALUE Program = rb_const_get(Airball, rb_intern("Program"));
  VALUE program = rb_obj_alloc(Program);
  rb_obj_call_init(program, 0, 0);
  rb_funcall(program, rb_intern("tree="), 1, *body);
  return program;
}
*/

/* not used
int main(int argc, char *argv[]) {
  init_ruby();
  rb_require("./lib/airball");

  parse(argv[1]);
  VALUE program = build_program(&body);

  return 0;
}
*/

