/* A recursive-descent parser generated by peg 0.1.2 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 33


#include "ruby.h"
RUBY_GLOBAL_SETUP;

FILE *source_file;

int yy_input(char *buf, int max_size);

#define YY_INPUT(b, r, ms) (r = yy_input(b, ms))

#define YYSTYPE volatile VALUE

VALUE parser; /* ruby obj */
VALUE stack; /* ruby array */

#define SPUSH() \
  rb_ary_push(stack, rb_ary_new())

#define SADD(val) \
  rb_ary_push(rb_ary_entry(stack, RARRAY_LEN(stack) - 1), val)

#define SPOP() \
  rb_ary_pop(stack)

#define P_NEW(n, v)           rb_funcall(parser, rb_intern(n), 1, v)
#define P_NEW2(n, v1, v2)     rb_funcall(parser, rb_intern(n), 2, v1, v2)
#define P_NEW3(n, v1, v2, v3) rb_funcall(parser, rb_intern(n), 3, v1, v2, v3)
#define P_ADD(ast)            rb_funcall(parser, rb_intern("add"), 1, ast)


#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      yybuflen *= 2;
      yybuf= realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if (yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yybuf+yypos));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yybuf+yypos));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end)
{
  while (yythunkpos >= yythunkslen)
    {
      yythunkslen *= 2;
      yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng - 1))
	{
	  yytextlen *= 2;
	  yytext= realloc(yytext, yytextlen);
	}
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_digit(); /* 33 */
YY_RULE(int) yy_esc(); /* 32 */
YY_RULE(int) yy_nsq(); /* 31 */
YY_RULE(int) yy_ndq(); /* 30 */
YY_RULE(int) yy_sq(); /* 29 */
YY_RULE(int) yy_dq(); /* 28 */
YY_RULE(int) yy_rangeop(); /* 27 */
YY_RULE(int) yy_integer(); /* 26 */
YY_RULE(int) yy_range(); /* 25 */
YY_RULE(int) yy_string(); /* 24 */
YY_RULE(int) yy_var(); /* 23 */
YY_RULE(int) yy_operand(); /* 22 */
YY_RULE(int) yy_func_args(); /* 21 */
YY_RULE(int) yy_atom(); /* 20 */
YY_RULE(int) yy_list(); /* 19 */
YY_RULE(int) yy_func(); /* 18 */
YY_RULE(int) yy_eop(); /* 17 */
YY_RULE(int) yy_op(); /* 16 */
YY_RULE(int) yy_ecall(); /* 15 */
YY_RULE(int) yy_arg_sep(); /* 14 */
YY_RULE(int) yy_symbol(); /* 13 */
YY_RULE(int) yy_identifier(); /* 12 */
YY_RULE(int) yy___(); /* 11 */
YY_RULE(int) yy_expr(); /* 10 */
YY_RULE(int) yy_assign(); /* 9 */
YY_RULE(int) yy_icall(); /* 8 */
YY_RULE(int) yy_comment(); /* 7 */
YY_RULE(int) yy_empty_line(); /* 6 */
YY_RULE(int) yy__(); /* 5 */
YY_RULE(int) yy_bad(); /* 4 */
YY_RULE(int) yy_eof(); /* 3 */
YY_RULE(int) yy_lexpr(); /* 2 */
YY_RULE(int) yy_body(); /* 1 */

YY_ACTION(void) yy_1_integer(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_integer\n"));
   yy = P_NEW("integer", rb_str_new(yytext, yyleng)); ;
}
YY_ACTION(void) yy_1_identifier(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_identifier\n"));
   yy = rb_str_new(yytext, yyleng); ;
}
YY_ACTION(void) yy_2_symbol(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_symbol\n"));
   yy = rb_str_new(yytext, yyleng); ;
}
YY_ACTION(void) yy_1_symbol(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_symbol\n"));
   yy = rb_str_new(yytext, yyleng); ;
}
YY_ACTION(void) yy_1_comment(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_comment\n"));
   yy = 0; ;
}
YY_ACTION(void) yy_1_empty_line(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_empty_line\n"));
   yy = 0; ;
}
YY_ACTION(void) yy_2_string(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_string\n"));
   yy = rb_str_new(yytext, yyleng); ;
}
YY_ACTION(void) yy_1_string(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_string\n"));
   yy = rb_str_new(yytext, yyleng); ;
}
YY_ACTION(void) yy_1_var(char *yytext, int yyleng)
{
#define name yyval[-1]
  yyprintf((stderr, "do yy_1_var\n"));
   yy = P_NEW("var", name); ;
#undef name
}
YY_ACTION(void) yy_1_range(char *yytext, int yyleng)
{
#define last yyval[-1]
#define first yyval[-2]
  yyprintf((stderr, "do yy_1_range\n"));
   yy = P_NEW2("range", first, last); ;
#undef last
#undef first
}
YY_ACTION(void) yy_3_list(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_3_list\n"));
   yy = P_NEW("list", SPOP()); ;
#undef e
}
YY_ACTION(void) yy_2_list(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_2_list\n"));
   SADD(e); ;
#undef e
}
YY_ACTION(void) yy_1_list(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_1_list\n"));
   SPUSH(); ;
#undef e
}
YY_ACTION(void) yy_1_atom(char *yytext, int yyleng)
{
#define str yyval[-1]
  yyprintf((stderr, "do yy_1_atom\n"));
   yy = P_NEW("string", str); ;
#undef str
}
YY_ACTION(void) yy_1_op(char *yytext, int yyleng)
{
#define right yyval[-1]
#define symbol yyval[-2]
#define left yyval[-3]
  yyprintf((stderr, "do yy_1_op\n"));
   yy = P_NEW3("op", symbol, left, right); ;
#undef right
#undef symbol
#undef left
}
YY_ACTION(void) yy_4_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_4_func_args\n"));
   yy = 0; ;
#undef arg
}
YY_ACTION(void) yy_3_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_3_func_args\n"));
   yy = SPOP(); ;
#undef arg
}
YY_ACTION(void) yy_2_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_2_func_args\n"));
   SADD(arg); ;
#undef arg
}
YY_ACTION(void) yy_1_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_1_func_args\n"));
   SPUSH(); ;
#undef arg
}
YY_ACTION(void) yy_3_func(char *yytext, int yyleng)
{
#define e yyval[-1]
#define args yyval[-2]
  yyprintf((stderr, "do yy_3_func\n"));
   yy = P_NEW2("func", args ? args : rb_ary_new(), SPOP()); ;
#undef e
#undef args
}
YY_ACTION(void) yy_2_func(char *yytext, int yyleng)
{
#define e yyval[-1]
#define args yyval[-2]
  yyprintf((stderr, "do yy_2_func\n"));
   e && SADD(e); ;
#undef e
#undef args
}
YY_ACTION(void) yy_1_func(char *yytext, int yyleng)
{
#define e yyval[-1]
#define args yyval[-2]
  yyprintf((stderr, "do yy_1_func\n"));
   SPUSH(); ;
#undef e
#undef args
}
YY_ACTION(void) yy_3_ecall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_3_ecall\n"));
   yy = P_NEW2("call", name, SPOP()); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_2_ecall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_2_ecall\n"));
   SADD(arg); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_1_ecall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_1_ecall\n"));
   SPUSH(); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_3_icall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_3_icall\n"));
   yy = P_NEW2("call", name, SPOP()); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_2_icall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_2_icall\n"));
   SADD(arg); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_1_icall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_1_icall\n"));
   SPUSH(); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_1_assign(char *yytext, int yyleng)
{
#define val yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_1_assign\n"));
   yy = P_NEW2("assign", name, val); ;
#undef val
#undef name
}
YY_ACTION(void) yy_1_bad(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bad\n"));
   P_ADD(P_NEW("syntax_error", rb_str_new(yytext, yyleng))); ;
}
YY_ACTION(void) yy_1_body(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_1_body\n"));
   e && P_ADD(e); ;
#undef e
}

YY_RULE(int) yy_digit()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "digit"));  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "digit", yybuf+yypos));
  return 1;
  l1:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "digit", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_esc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "esc"));  if (!yymatchChar('\\')) goto l2;  if (!yymatchDot()) goto l2;
  yyprintf((stderr, "  ok   %s @ %s\n", "esc", yybuf+yypos));
  return 1;
  l2:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "esc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_nsq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "nsq"));
  {  int yypos4= yypos, yythunkpos4= yythunkpos;  if (!yy_sq()) goto l4;  goto l3;
  l4:;	  yypos= yypos4; yythunkpos= yythunkpos4;
  }  if (!yymatchDot()) goto l3;
  yyprintf((stderr, "  ok   %s @ %s\n", "nsq", yybuf+yypos));
  return 1;
  l3:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "nsq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ndq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "ndq"));
  {  int yypos6= yypos, yythunkpos6= yythunkpos;  if (!yy_dq()) goto l6;  goto l5;
  l6:;	  yypos= yypos6; yythunkpos= yythunkpos6;
  }  if (!yymatchDot()) goto l5;
  yyprintf((stderr, "  ok   %s @ %s\n", "ndq", yybuf+yypos));
  return 1;
  l5:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ndq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_sq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "sq"));  if (!yymatchChar('\'')) goto l7;
  yyprintf((stderr, "  ok   %s @ %s\n", "sq", yybuf+yypos));
  return 1;
  l7:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_dq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "dq"));  if (!yymatchChar('\"')) goto l8;
  yyprintf((stderr, "  ok   %s @ %s\n", "dq", yybuf+yypos));
  return 1;
  l8:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "dq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_rangeop()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "rangeop"));
  {  int yypos10= yypos, yythunkpos10= yythunkpos;  if (!yy_var()) goto l11;  goto l10;
  l11:;	  yypos= yypos10; yythunkpos= yythunkpos10;  if (!yy_integer()) goto l12;  goto l10;
  l12:;	  yypos= yypos10; yythunkpos= yythunkpos10;  if (!yy_eop()) goto l13;  goto l10;
  l13:;	  yypos= yypos10; yythunkpos= yythunkpos10;  if (!yy_ecall()) goto l9;
  }
  l10:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "rangeop", yybuf+yypos));
  return 1;
  l9:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "rangeop", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_integer()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "integer"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l14;  if (!yy_digit()) goto l14;
  l15:;	
  {  int yypos16= yypos, yythunkpos16= yythunkpos;  if (!yy_digit()) goto l16;  goto l15;
  l16:;	  yypos= yypos16; yythunkpos= yythunkpos16;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l14;  yyDo(yy_1_integer, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "integer", yybuf+yypos));
  return 1;
  l14:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "integer", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_range()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "range"));  if (!yy_rangeop()) goto l17;  yyDo(yySet, -2, 0);  if (!yymatchString("..")) goto l17;  if (!yy_rangeop()) goto l17;  yyDo(yySet, -1, 0);  yyDo(yy_1_range, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "range", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l17:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "range", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_string()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "string"));
  {  int yypos19= yypos, yythunkpos19= yythunkpos;  if (!yy_dq()) goto l20;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l20;
  l21:;	
  {  int yypos22= yypos, yythunkpos22= yythunkpos;
  {  int yypos23= yypos, yythunkpos23= yythunkpos;  if (!yy_esc()) goto l24;  goto l23;
  l24:;	  yypos= yypos23; yythunkpos= yythunkpos23;  if (!yy_ndq()) goto l22;
  }
  l23:;	  goto l21;
  l22:;	  yypos= yypos22; yythunkpos= yythunkpos22;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l20;  if (!yy_dq()) goto l20;  yyDo(yy_1_string, yybegin, yyend);  goto l19;
  l20:;	  yypos= yypos19; yythunkpos= yythunkpos19;  if (!yy_sq()) goto l18;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l18;
  l25:;	
  {  int yypos26= yypos, yythunkpos26= yythunkpos;
  {  int yypos27= yypos, yythunkpos27= yythunkpos;  if (!yy_esc()) goto l28;  goto l27;
  l28:;	  yypos= yypos27; yythunkpos= yythunkpos27;  if (!yy_nsq()) goto l26;
  }
  l27:;	  goto l25;
  l26:;	  yypos= yypos26; yythunkpos= yythunkpos26;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l18;  if (!yy_sq()) goto l18;  yyDo(yy_2_string, yybegin, yyend);
  }
  l19:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "string", yybuf+yypos));
  return 1;
  l18:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "string", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_var()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "var"));  if (!yy_identifier()) goto l29;  yyDo(yySet, -1, 0);  yyDo(yy_1_var, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "var", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l29:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "var", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_operand()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "operand"));
  {  int yypos31= yypos, yythunkpos31= yythunkpos;  if (!yy_list()) goto l32;  goto l31;
  l32:;	  yypos= yypos31; yythunkpos= yythunkpos31;  if (!yy_atom()) goto l33;  goto l31;
  l33:;	  yypos= yypos31; yythunkpos= yythunkpos31;  if (!yy_eop()) goto l34;  goto l31;
  l34:;	  yypos= yypos31; yythunkpos= yythunkpos31;  if (!yy_ecall()) goto l30;
  }
  l31:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "operand", yybuf+yypos));
  return 1;
  l30:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "operand", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_func_args()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "func_args"));
  {  int yypos36= yypos, yythunkpos36= yythunkpos;  if (!yymatchChar('[')) goto l37;  yyDo(yy_1_func_args, yybegin, yyend);
  l40:;	
  {  int yypos41= yypos, yythunkpos41= yythunkpos;  if (!yy__()) goto l41;  goto l40;
  l41:;	  yypos= yypos41; yythunkpos= yythunkpos41;
  }  if (!yy_identifier()) goto l37;  yyDo(yySet, -1, 0);  yyDo(yy_2_func_args, yybegin, yyend);
  l38:;	
  {  int yypos39= yypos, yythunkpos39= yythunkpos;
  l42:;	
  {  int yypos43= yypos, yythunkpos43= yythunkpos;  if (!yy__()) goto l43;  goto l42;
  l43:;	  yypos= yypos43; yythunkpos= yythunkpos43;
  }  if (!yy_identifier()) goto l39;  yyDo(yySet, -1, 0);  yyDo(yy_2_func_args, yybegin, yyend);  goto l38;
  l39:;	  yypos= yypos39; yythunkpos= yythunkpos39;
  }
  l44:;	
  {  int yypos45= yypos, yythunkpos45= yythunkpos;  if (!yy__()) goto l45;  goto l44;
  l45:;	  yypos= yypos45; yythunkpos= yythunkpos45;
  }  if (!yymatchChar(']')) goto l37;
  l46:;	
  {  int yypos47= yypos, yythunkpos47= yythunkpos;  if (!yy__()) goto l47;  goto l46;
  l47:;	  yypos= yypos47; yythunkpos= yythunkpos47;
  }  yyDo(yy_3_func_args, yybegin, yyend);  goto l36;
  l37:;	  yypos= yypos36; yythunkpos= yythunkpos36;
  {  int yypos48= yypos, yythunkpos48= yythunkpos;  if (!yymatchChar('{')) goto l35;  yypos= yypos48; yythunkpos= yythunkpos48;
  }  yyDo(yy_4_func_args, yybegin, yyend);
  }
  l36:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "func_args", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l35:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "func_args", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_atom()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "atom"));
  {  int yypos50= yypos, yythunkpos50= yythunkpos;  if (!yy_var()) goto l51;  goto l50;
  l51:;	  yypos= yypos50; yythunkpos= yythunkpos50;  if (!yy_string()) goto l52;  yyDo(yySet, -1, 0);  yyDo(yy_1_atom, yybegin, yyend);  goto l50;
  l52:;	  yypos= yypos50; yythunkpos= yythunkpos50;  if (!yy_range()) goto l53;  goto l50;
  l53:;	  yypos= yypos50; yythunkpos= yythunkpos50;  if (!yy_integer()) goto l49;
  }
  l50:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "atom", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l49:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "atom", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "list"));  if (!yymatchChar('[')) goto l54;
  l55:;	
  {  int yypos56= yypos, yythunkpos56= yythunkpos;  if (!yy__()) goto l56;  goto l55;
  l56:;	  yypos= yypos56; yythunkpos= yythunkpos56;
  }  yyDo(yy_1_list, yybegin, yyend);
  l57:;	
  {  int yypos58= yypos, yythunkpos58= yythunkpos;  if (!yy_expr()) goto l58;  yyDo(yySet, -1, 0);
  l59:;	
  {  int yypos60= yypos, yythunkpos60= yythunkpos;
  {  int yypos61= yypos, yythunkpos61= yythunkpos;  if (!yy__()) goto l62;  goto l61;
  l62:;	  yypos= yypos61; yythunkpos= yythunkpos61;  if (!yy___()) goto l60;
  }
  l61:;	  goto l59;
  l60:;	  yypos= yypos60; yythunkpos= yythunkpos60;
  }  yyDo(yy_2_list, yybegin, yyend);  goto l57;
  l58:;	  yypos= yypos58; yythunkpos= yythunkpos58;
  }  if (!yymatchChar(']')) goto l54;  yyDo(yy_3_list, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "list", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l54:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "list", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_func()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "func"));  if (!yy_func_args()) goto l63;  yyDo(yySet, -2, 0);  if (!yymatchChar('{')) goto l63;
  l64:;	
  {  int yypos65= yypos, yythunkpos65= yythunkpos;
  {  int yypos66= yypos, yythunkpos66= yythunkpos;  if (!yy__()) goto l67;  goto l66;
  l67:;	  yypos= yypos66; yythunkpos= yythunkpos66;  if (!yy___()) goto l65;
  }
  l66:;	  goto l64;
  l65:;	  yypos= yypos65; yythunkpos= yythunkpos65;
  }  yyDo(yy_1_func, yybegin, yyend);  if (!yy_lexpr()) goto l63;  yyDo(yySet, -1, 0);  yyDo(yy_2_func, yybegin, yyend);
  l68:;	
  {  int yypos69= yypos, yythunkpos69= yythunkpos;  if (!yy_lexpr()) goto l69;  yyDo(yySet, -1, 0);  yyDo(yy_2_func, yybegin, yyend);  goto l68;
  l69:;	  yypos= yypos69; yythunkpos= yythunkpos69;
  }
  l70:;	
  {  int yypos71= yypos, yythunkpos71= yythunkpos;  if (!yy__()) goto l71;  goto l70;
  l71:;	  yypos= yypos71; yythunkpos= yythunkpos71;
  }  if (!yymatchChar('}')) goto l63;  yyDo(yy_3_func, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "func", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l63:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "func", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eop()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eop"));  if (!yymatchChar('(')) goto l72;  if (!yy_op()) goto l72;  if (!yymatchChar(')')) goto l72;
  yyprintf((stderr, "  ok   %s @ %s\n", "eop", yybuf+yypos));
  return 1;
  l72:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eop", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_op()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "op"));  if (!yy_operand()) goto l73;  yyDo(yySet, -3, 0);  if (!yy__()) goto l73;
  l74:;	
  {  int yypos75= yypos, yythunkpos75= yythunkpos;  if (!yy__()) goto l75;  goto l74;
  l75:;	  yypos= yypos75; yythunkpos= yythunkpos75;
  }  if (!yy_symbol()) goto l73;  yyDo(yySet, -2, 0);  if (!yy__()) goto l73;
  l76:;	
  {  int yypos77= yypos, yythunkpos77= yythunkpos;  if (!yy__()) goto l77;  goto l76;
  l77:;	  yypos= yypos77; yythunkpos= yythunkpos77;
  }  if (!yy_operand()) goto l73;  yyDo(yySet, -1, 0);  yyDo(yy_1_op, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "op", yybuf+yypos));  yyDo(yyPop, 3, 0);
  return 1;
  l73:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "op", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ecall()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "ecall"));  if (!yymatchChar('(')) goto l78;  if (!yy_identifier()) goto l78;  yyDo(yySet, -2, 0);  yyDo(yy_1_ecall, yybegin, yyend);
  l79:;	
  {  int yypos80= yypos, yythunkpos80= yythunkpos;  if (!yy_arg_sep()) goto l80;  if (!yy_expr()) goto l80;  yyDo(yySet, -1, 0);  yyDo(yy_2_ecall, yybegin, yyend);  goto l79;
  l80:;	  yypos= yypos80; yythunkpos= yythunkpos80;
  }  if (!yymatchChar(')')) goto l78;  yyDo(yy_3_ecall, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "ecall", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l78:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ecall", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_arg_sep()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "arg_sep"));
  {  int yypos82= yypos, yythunkpos82= yythunkpos;  if (!yymatchChar(',')) goto l83;
  l84:;	
  {  int yypos85= yypos, yythunkpos85= yythunkpos;
  {  int yypos86= yypos, yythunkpos86= yythunkpos;  if (!yy__()) goto l87;  goto l86;
  l87:;	  yypos= yypos86; yythunkpos= yythunkpos86;  if (!yy___()) goto l85;
  }
  l86:;	  goto l84;
  l85:;	  yypos= yypos85; yythunkpos= yythunkpos85;
  }  goto l82;
  l83:;	  yypos= yypos82; yythunkpos= yythunkpos82;  if (!yy__()) goto l81;
  l88:;	
  {  int yypos89= yypos, yythunkpos89= yythunkpos;  if (!yy__()) goto l89;  goto l88;
  l89:;	  yypos= yypos89; yythunkpos= yythunkpos89;
  }
  }
  l82:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "arg_sep", yybuf+yypos));
  return 1;
  l81:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "arg_sep", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_symbol()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "symbol"));
  {  int yypos91= yypos, yythunkpos91= yythunkpos;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l92;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\320\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l92;
  l93:;	
  {  int yypos94= yypos, yythunkpos94= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\320\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l94;  goto l93;
  l94:;	  yypos= yypos94; yythunkpos= yythunkpos94;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l92;  yyDo(yy_1_symbol, yybegin, yyend);  goto l91;
  l92:;	  yypos= yypos91; yythunkpos= yythunkpos91;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l90;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\360\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l90;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\360\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l90;
  l95:;	
  {  int yypos96= yypos, yythunkpos96= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\360\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l96;  goto l95;
  l96:;	  yypos= yypos96; yythunkpos= yythunkpos96;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l90;  yyDo(yy_2_symbol, yybegin, yyend);
  }
  l91:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "symbol", yybuf+yypos));
  return 1;
  l90:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "symbol", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_identifier()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "identifier"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l97;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l97;
  l98:;	
  {  int yypos99= yypos, yythunkpos99= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\040\377\003\000\000\000\000\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l99;  goto l98;
  l99:;	  yypos= yypos99; yythunkpos= yythunkpos99;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l97;  yyDo(yy_1_identifier, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "identifier", yybuf+yypos));
  return 1;
  l97:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "identifier", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy___()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "__"));
  {  int yypos101= yypos, yythunkpos101= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l101;  goto l102;
  l101:;	  yypos= yypos101; yythunkpos= yythunkpos101;
  }
  l102:;	  if (!yymatchClass((unsigned char *)"\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l100;
  yyprintf((stderr, "  ok   %s @ %s\n", "__", yybuf+yypos));
  return 1;
  l100:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "__", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_expr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "expr"));
  {  int yypos104= yypos, yythunkpos104= yythunkpos;  if (!yy_op()) goto l105;  goto l104;
  l105:;	  yypos= yypos104; yythunkpos= yythunkpos104;  if (!yy_eop()) goto l106;  goto l104;
  l106:;	  yypos= yypos104; yythunkpos= yythunkpos104;  if (!yy_ecall()) goto l107;  goto l104;
  l107:;	  yypos= yypos104; yythunkpos= yythunkpos104;  if (!yy_func()) goto l108;  goto l104;
  l108:;	  yypos= yypos104; yythunkpos= yythunkpos104;  if (!yy_list()) goto l109;  goto l104;
  l109:;	  yypos= yypos104; yythunkpos= yythunkpos104;  if (!yy_atom()) goto l103;
  }
  l104:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "expr", yybuf+yypos));
  return 1;
  l103:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "expr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_assign()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "assign"));
  {  int yypos111= yypos, yythunkpos111= yythunkpos;  if (!yy_identifier()) goto l112;  yyDo(yySet, -2, 0);  goto l111;
  l112:;	  yypos= yypos111; yythunkpos= yythunkpos111;  if (!yy_symbol()) goto l110;  yyDo(yySet, -2, 0);
  }
  l111:;	  if (!yy__()) goto l110;
  l113:;	
  {  int yypos114= yypos, yythunkpos114= yythunkpos;  if (!yy__()) goto l114;  goto l113;
  l114:;	  yypos= yypos114; yythunkpos= yythunkpos114;
  }  if (!yymatchChar('=')) goto l110;  if (!yy__()) goto l110;
  l115:;	
  {  int yypos116= yypos, yythunkpos116= yythunkpos;  if (!yy__()) goto l116;  goto l115;
  l116:;	  yypos= yypos116; yythunkpos= yythunkpos116;
  }
  {  int yypos117= yypos, yythunkpos117= yythunkpos;  if (!yy_icall()) goto l118;  yyDo(yySet, -1, 0);  goto l117;
  l118:;	  yypos= yypos117; yythunkpos= yythunkpos117;  if (!yy_expr()) goto l110;  yyDo(yySet, -1, 0);
  }
  l117:;	  yyDo(yy_1_assign, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "assign", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l110:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "assign", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_icall()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "icall"));  if (!yy_identifier()) goto l119;  yyDo(yySet, -2, 0);  yyDo(yy_1_icall, yybegin, yyend);  if (!yy_arg_sep()) goto l119;  if (!yy_expr()) goto l119;  yyDo(yySet, -1, 0);  yyDo(yy_2_icall, yybegin, yyend);
  l120:;	
  {  int yypos121= yypos, yythunkpos121= yythunkpos;  if (!yy_arg_sep()) goto l121;  if (!yy_expr()) goto l121;  yyDo(yySet, -1, 0);  yyDo(yy_2_icall, yybegin, yyend);  goto l120;
  l121:;	  yypos= yypos121; yythunkpos= yythunkpos121;
  }  yyDo(yy_3_icall, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "icall", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l119:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "icall", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_comment()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "comment"));
  l123:;	
  {  int yypos124= yypos, yythunkpos124= yythunkpos;  if (!yy__()) goto l124;  goto l123;
  l124:;	  yypos= yypos124; yythunkpos= yythunkpos124;
  }  if (!yymatchChar('#')) goto l122;
  l125:;	
  {  int yypos126= yypos, yythunkpos126= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\333\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l126;  goto l125;
  l126:;	  yypos= yypos126; yythunkpos= yythunkpos126;
  }
  {  int yypos127= yypos, yythunkpos127= yythunkpos;  if (!yy___()) goto l127;  goto l128;
  l127:;	  yypos= yypos127; yythunkpos= yythunkpos127;
  }
  l128:;	  yyDo(yy_1_comment, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "comment", yybuf+yypos));
  return 1;
  l122:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "comment", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_empty_line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "empty_line"));
  l130:;	
  {  int yypos131= yypos, yythunkpos131= yythunkpos;  if (!yy__()) goto l131;  goto l130;
  l131:;	  yypos= yypos131; yythunkpos= yythunkpos131;
  }  if (!yy___()) goto l129;  yyDo(yy_1_empty_line, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "empty_line", yybuf+yypos));
  return 1;
  l129:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "empty_line", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy__()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "_"));  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l132;
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yybuf+yypos));
  return 1;
  l132:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "_", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bad()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bad"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l133;  if (!yymatchDot()) goto l133;
  l134:;	
  {  int yypos135= yypos, yythunkpos135= yythunkpos;  if (!yymatchDot()) goto l135;  goto l134;
  l135:;	  yypos= yypos135; yythunkpos= yythunkpos135;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l133;  yyDo(yy_1_bad, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bad", yybuf+yypos));
  return 1;
  l133:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bad", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eof()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eof"));
  {  int yypos137= yypos, yythunkpos137= yythunkpos;  if (!yymatchDot()) goto l137;  goto l136;
  l137:;	  yypos= yypos137; yythunkpos= yythunkpos137;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "eof", yybuf+yypos));
  return 1;
  l136:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eof", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_lexpr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "lexpr"));
  l139:;	
  {  int yypos140= yypos, yythunkpos140= yythunkpos;  if (!yy__()) goto l140;  goto l139;
  l140:;	  yypos= yypos140; yythunkpos= yythunkpos140;
  }
  {  int yypos141= yypos, yythunkpos141= yythunkpos;  if (!yy_empty_line()) goto l142;  goto l141;
  l142:;	  yypos= yypos141; yythunkpos= yythunkpos141;  if (!yy_comment()) goto l143;  goto l141;
  l143:;	  yypos= yypos141; yythunkpos= yythunkpos141;  if (!yy_icall()) goto l144;  goto l141;
  l144:;	  yypos= yypos141; yythunkpos= yythunkpos141;  if (!yy_assign()) goto l145;  goto l141;
  l145:;	  yypos= yypos141; yythunkpos= yythunkpos141;  if (!yy_expr()) goto l138;
  }
  l141:;	
  l146:;	
  {  int yypos147= yypos, yythunkpos147= yythunkpos;  if (!yy__()) goto l147;  goto l146;
  l147:;	  yypos= yypos147; yythunkpos= yythunkpos147;
  }
  {  int yypos148= yypos, yythunkpos148= yythunkpos;  if (!yy___()) goto l148;  goto l149;
  l148:;	  yypos= yypos148; yythunkpos= yythunkpos148;
  }
  l149:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "lexpr", yybuf+yypos));
  return 1;
  l138:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "lexpr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_body()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "body"));
  {  int yypos151= yypos, yythunkpos151= yythunkpos;  if (!yy_lexpr()) goto l152;  yyDo(yySet, -1, 0);  yyDo(yy_1_body, yybegin, yyend);
  l153:;	
  {  int yypos154= yypos, yythunkpos154= yythunkpos;  if (!yy_lexpr()) goto l154;  yyDo(yySet, -1, 0);  yyDo(yy_1_body, yybegin, yyend);  goto l153;
  l154:;	  yypos= yypos154; yythunkpos= yythunkpos154;
  }  if (!yy_eof()) goto l152;  goto l151;
  l152:;	  yypos= yypos151; yythunkpos= yythunkpos151;
  l155:;	
  {  int yypos156= yypos, yythunkpos156= yythunkpos;  if (!yy_lexpr()) goto l156;  goto l155;
  l156:;	  yypos= yypos156; yythunkpos= yythunkpos156;
  }  if (!yy_bad()) goto l150;  if (!yy_eof()) goto l150;
  }
  l151:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "body", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l150:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "body", yybuf+yypos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= malloc(yybuflen);
      yytextlen= 1024;
      yytext= malloc(yytextlen);
      yythunkslen= 32;
      yythunks= malloc(sizeof(yythunk) * yythunkslen);
      yyvalslen= 32;
      yyvals= malloc(sizeof(YYSTYPE) * yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_body);
}

#endif


/* borrowed from O'Reilly book "lex & yacc" pg. 157 */
char *yy_input_ptr;
int yy_input_len;

int yy_input(char *buf, int max_size) {
  int len = strlen(yy_input_ptr);
  int n = max_size < len ? max_size : len;
  if(n > 0) {
    memcpy(buf, yy_input_ptr, n);
    yy_input_ptr += n;
  }
  return n;
}

static VALUE rb_cParser_parse(VALUE self, VALUE source) {
  VALUE rb_cGC = rb_const_get(rb_cObject, rb_intern("GC"));
  rb_funcall(rb_cGC, rb_intern("disable"), 0, 0);
  yy_input_ptr = rb_string_value_cstr(&source);
  yy_input_len = strlen(yy_input_ptr);
  stack = rb_ary_new();
  parser = self;
  rb_iv_set(self, "@expressions", rb_ary_new());
  while (yyparse());
  rb_funcall(rb_cGC, rb_intern("enable"), 0, 0);
  return rb_iv_get(self, "@expressions");
}

void Init_parser() {
  VALUE rb_mAirball = rb_const_get(rb_cObject, rb_intern("Airball"));
  VALUE rb_cParser = rb_const_get(rb_mAirball, rb_intern("Parser"));
  rb_define_method(rb_cParser, "parse", rb_cParser_parse, 1);
  rb_gc_register_address(&stack);
}

