/* A recursive-descent parser generated by peg 0.1.7 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 32

#include "lidija.h"
int l_stackp = 0;

#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      yybuflen *= 2;
      yybuf= realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if ((unsigned char)yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yybuf+yypos));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= (unsigned char)yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yybuf+yypos));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end)
{
  while (yythunkpos >= yythunkslen)
    {
      yythunkslen *= 2;
      yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng + 1))
	{
	  yytextlen *= 2;
	  yytext= realloc(yytext, yytextlen);
	}
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_digit(); /* 32 */
YY_RULE(int) yy_esc(); /* 31 */
YY_RULE(int) yy_nsq(); /* 30 */
YY_RULE(int) yy_ndq(); /* 29 */
YY_RULE(int) yy_sq(); /* 28 */
YY_RULE(int) yy_dq(); /* 27 */
YY_RULE(int) yy_list_sep(); /* 26 */
YY_RULE(int) yy_integer(); /* 25 */
YY_RULE(int) yy_string(); /* 24 */
YY_RULE(int) yy_var(); /* 23 */
YY_RULE(int) yy_operand(); /* 22 */
YY_RULE(int) yy_func_args(); /* 21 */
YY_RULE(int) yy_atom(); /* 20 */
YY_RULE(int) yy_list(); /* 19 */
YY_RULE(int) yy_func(); /* 18 */
YY_RULE(int) yy_eop(); /* 17 */
YY_RULE(int) yy_op(); /* 16 */
YY_RULE(int) yy_ecall(); /* 15 */
YY_RULE(int) yy_arg_sep(); /* 14 */
YY_RULE(int) yy_symbol(); /* 13 */
YY_RULE(int) yy_identifier(); /* 12 */
YY_RULE(int) yy___(); /* 11 */
YY_RULE(int) yy_expr(); /* 10 */
YY_RULE(int) yy_assign(); /* 9 */
YY_RULE(int) yy_icall(); /* 8 */
YY_RULE(int) yy_comment(); /* 7 */
YY_RULE(int) yy_empty_line(); /* 6 */
YY_RULE(int) yy__(); /* 5 */
YY_RULE(int) yy_bad(); /* 4 */
YY_RULE(int) yy_eof(); /* 3 */
YY_RULE(int) yy_lexpr(); /* 2 */
YY_RULE(int) yy_body(); /* 1 */

YY_ACTION(void) yy_1_integer(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_integer\n"));
   yy = l_create_int_node(yytext, yyleng); ;
}
YY_ACTION(void) yy_1_identifier(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_identifier\n"));
   yy = yytos(yytext, yyleng); ;
}
YY_ACTION(void) yy_2_symbol(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_symbol\n"));
   yy = yytos(yytext, yyleng); ;
}
YY_ACTION(void) yy_1_symbol(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_symbol\n"));
   yy = yytos(yytext, yyleng); ;
}
YY_ACTION(void) yy_1_comment(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_comment\n"));
   yy = 0; ;
}
YY_ACTION(void) yy_1_empty_line(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_empty_line\n"));
   yy = 0; ;
}
YY_ACTION(void) yy_2_string(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_string\n"));
   yy = l_create_str_node(yytext, yyleng); ;
}
YY_ACTION(void) yy_1_string(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_string\n"));
   yy = l_create_str_node(yytext, yyleng); ;
}
YY_ACTION(void) yy_1_var(char *yytext, int yyleng)
{
#define name yyval[-1]
  yyprintf((stderr, "do yy_1_var\n"));
   yy = l_create_var_node(name); ;
#undef name
}
YY_ACTION(void) yy_3_list(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_3_list\n"));
   int count = l_stack_count[l_stackp];
                                                     yy = l_create_list_node(count, l_stack_pop()); ;
#undef e
}
YY_ACTION(void) yy_2_list(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_2_list\n"));
   l_stack_add(e); ;
#undef e
}
YY_ACTION(void) yy_1_list(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_1_list\n"));
   l_stack_push(); ;
#undef e
}
YY_ACTION(void) yy_1_op(char *yytext, int yyleng)
{
#define right yyval[-1]
#define symbol yyval[-2]
#define left yyval[-3]
  yyprintf((stderr, "do yy_1_op\n"));
   LNode **args = malloc(sizeof(LNode*) * 2);
                                                     args[0] = left;
                                                     args[1] = right;
                                                     yy = l_create_call_node(symbol, 2, args); ;
#undef right
#undef symbol
#undef left
}
YY_ACTION(void) yy_4_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_4_func_args\n"));
   yy = l_create_list_node(0, NULL); ;
#undef arg
}
YY_ACTION(void) yy_3_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_3_func_args\n"));
   int count = l_stack_count[l_stackp];
                                                     yy = l_create_list_node(count, l_stack_pop()); ;
#undef arg
}
YY_ACTION(void) yy_2_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_2_func_args\n"));
   l_stack_add(l_create_var_node(arg)); ;
#undef arg
}
YY_ACTION(void) yy_1_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_1_func_args\n"));
   l_stack_push(); ;
#undef arg
}
YY_ACTION(void) yy_3_func(char *yytext, int yyleng)
{
#define e yyval[-1]
#define args yyval[-2]
  yyprintf((stderr, "do yy_3_func\n"));
   int count = l_stack_count[l_stackp];
                                                     yy = l_create_func_node(args, count, l_stack_pop()); ;
#undef e
#undef args
}
YY_ACTION(void) yy_2_func(char *yytext, int yyleng)
{
#define e yyval[-1]
#define args yyval[-2]
  yyprintf((stderr, "do yy_2_func\n"));
   if(e) l_stack_add(e); ;
#undef e
#undef args
}
YY_ACTION(void) yy_1_func(char *yytext, int yyleng)
{
#define e yyval[-1]
#define args yyval[-2]
  yyprintf((stderr, "do yy_1_func\n"));
   l_stack_push(); ;
#undef e
#undef args
}
YY_ACTION(void) yy_3_ecall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_3_ecall\n"));
   int count = l_stack_count[l_stackp];
                                                     yy = l_create_call_node(name, count, l_stack_pop()); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_2_ecall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_2_ecall\n"));
   l_stack_add(arg); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_1_ecall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_1_ecall\n"));
   l_stack_push(); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_3_icall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_3_icall\n"));
   int count = l_stack_count[l_stackp];
                                                     yy = l_create_call_node(name, count, l_stack_pop()); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_2_icall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_2_icall\n"));
   l_stack_add(arg); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_1_icall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_1_icall\n"));
   l_stack_push(); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_1_assign(char *yytext, int yyleng)
{
#define val yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_1_assign\n"));
   yy = l_create_assign_node(name, val); ;
#undef val
#undef name
}
YY_ACTION(void) yy_1_bad(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bad\n"));
   l_ast_add_node(l_create_err_node(yytos(yytext, yyleng))); ;
}
YY_ACTION(void) yy_1_body(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_1_body\n"));
   if(e) l_ast_add_node(e); ;
#undef e
}

YY_RULE(int) yy_digit()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "digit"));  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "digit", yybuf+yypos));
  return 1;
  l1:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "digit", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_esc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "esc"));  if (!yymatchChar('\\')) goto l2;  if (!yymatchDot()) goto l2;
  yyprintf((stderr, "  ok   %s @ %s\n", "esc", yybuf+yypos));
  return 1;
  l2:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "esc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_nsq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "nsq"));
  {  int yypos4= yypos, yythunkpos4= yythunkpos;  if (!yy_sq()) goto l4;  goto l3;
  l4:;	  yypos= yypos4; yythunkpos= yythunkpos4;
  }  if (!yymatchDot()) goto l3;
  yyprintf((stderr, "  ok   %s @ %s\n", "nsq", yybuf+yypos));
  return 1;
  l3:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "nsq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ndq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "ndq"));
  {  int yypos6= yypos, yythunkpos6= yythunkpos;  if (!yy_dq()) goto l6;  goto l5;
  l6:;	  yypos= yypos6; yythunkpos= yythunkpos6;
  }  if (!yymatchDot()) goto l5;
  yyprintf((stderr, "  ok   %s @ %s\n", "ndq", yybuf+yypos));
  return 1;
  l5:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ndq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_sq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "sq"));  if (!yymatchChar('\'')) goto l7;
  yyprintf((stderr, "  ok   %s @ %s\n", "sq", yybuf+yypos));
  return 1;
  l7:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_dq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "dq"));  if (!yymatchChar('\"')) goto l8;
  yyprintf((stderr, "  ok   %s @ %s\n", "dq", yybuf+yypos));
  return 1;
  l8:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "dq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_list_sep()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "list_sep"));
  {  int yypos10= yypos, yythunkpos10= yythunkpos;  if (!yy__()) goto l11;  goto l10;
  l11:;	  yypos= yypos10; yythunkpos= yythunkpos10;  if (!yy___()) goto l12;  goto l10;
  l12:;	  yypos= yypos10; yythunkpos= yythunkpos10;  if (!yymatchChar(',')) goto l9;
  }
  l10:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "list_sep", yybuf+yypos));
  return 1;
  l9:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "list_sep", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_integer()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "integer"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l13;  if (!yy_digit()) goto l13;
  l14:;	
  {  int yypos15= yypos, yythunkpos15= yythunkpos;  if (!yy_digit()) goto l15;  goto l14;
  l15:;	  yypos= yypos15; yythunkpos= yythunkpos15;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l13;  yyDo(yy_1_integer, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "integer", yybuf+yypos));
  return 1;
  l13:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "integer", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_string()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "string"));
  {  int yypos17= yypos, yythunkpos17= yythunkpos;  if (!yy_dq()) goto l18;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l18;
  l19:;	
  {  int yypos20= yypos, yythunkpos20= yythunkpos;
  {  int yypos21= yypos, yythunkpos21= yythunkpos;  if (!yy_esc()) goto l22;  goto l21;
  l22:;	  yypos= yypos21; yythunkpos= yythunkpos21;  if (!yy_ndq()) goto l20;
  }
  l21:;	  goto l19;
  l20:;	  yypos= yypos20; yythunkpos= yythunkpos20;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l18;  if (!yy_dq()) goto l18;  yyDo(yy_1_string, yybegin, yyend);  goto l17;
  l18:;	  yypos= yypos17; yythunkpos= yythunkpos17;  if (!yy_sq()) goto l16;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l16;
  l23:;	
  {  int yypos24= yypos, yythunkpos24= yythunkpos;
  {  int yypos25= yypos, yythunkpos25= yythunkpos;  if (!yy_esc()) goto l26;  goto l25;
  l26:;	  yypos= yypos25; yythunkpos= yythunkpos25;  if (!yy_nsq()) goto l24;
  }
  l25:;	  goto l23;
  l24:;	  yypos= yypos24; yythunkpos= yythunkpos24;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l16;  if (!yy_sq()) goto l16;  yyDo(yy_2_string, yybegin, yyend);
  }
  l17:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "string", yybuf+yypos));
  return 1;
  l16:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "string", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_var()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "var"));  if (!yy_identifier()) goto l27;  yyDo(yySet, -1, 0);  yyDo(yy_1_var, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "var", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l27:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "var", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_operand()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "operand"));
  {  int yypos29= yypos, yythunkpos29= yythunkpos;  if (!yy_list()) goto l30;  goto l29;
  l30:;	  yypos= yypos29; yythunkpos= yythunkpos29;  if (!yy_atom()) goto l31;  goto l29;
  l31:;	  yypos= yypos29; yythunkpos= yythunkpos29;  if (!yy_eop()) goto l32;  goto l29;
  l32:;	  yypos= yypos29; yythunkpos= yythunkpos29;  if (!yy_ecall()) goto l28;
  }
  l29:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "operand", yybuf+yypos));
  return 1;
  l28:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "operand", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_func_args()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "func_args"));
  {  int yypos34= yypos, yythunkpos34= yythunkpos;  if (!yymatchChar('[')) goto l35;  yyDo(yy_1_func_args, yybegin, yyend);
  l38:;	
  {  int yypos39= yypos, yythunkpos39= yythunkpos;  if (!yy__()) goto l39;  goto l38;
  l39:;	  yypos= yypos39; yythunkpos= yythunkpos39;
  }  if (!yy_identifier()) goto l35;  yyDo(yySet, -1, 0);  yyDo(yy_2_func_args, yybegin, yyend);
  l36:;	
  {  int yypos37= yypos, yythunkpos37= yythunkpos;
  l40:;	
  {  int yypos41= yypos, yythunkpos41= yythunkpos;  if (!yy__()) goto l41;  goto l40;
  l41:;	  yypos= yypos41; yythunkpos= yythunkpos41;
  }  if (!yy_identifier()) goto l37;  yyDo(yySet, -1, 0);  yyDo(yy_2_func_args, yybegin, yyend);  goto l36;
  l37:;	  yypos= yypos37; yythunkpos= yythunkpos37;
  }
  l42:;	
  {  int yypos43= yypos, yythunkpos43= yythunkpos;  if (!yy__()) goto l43;  goto l42;
  l43:;	  yypos= yypos43; yythunkpos= yythunkpos43;
  }  if (!yymatchChar(']')) goto l35;
  l44:;	
  {  int yypos45= yypos, yythunkpos45= yythunkpos;  if (!yy__()) goto l45;  goto l44;
  l45:;	  yypos= yypos45; yythunkpos= yythunkpos45;
  }  yyDo(yy_3_func_args, yybegin, yyend);  goto l34;
  l35:;	  yypos= yypos34; yythunkpos= yythunkpos34;
  {  int yypos46= yypos, yythunkpos46= yythunkpos;  if (!yymatchChar('{')) goto l33;  yypos= yypos46; yythunkpos= yythunkpos46;
  }  yyDo(yy_4_func_args, yybegin, yyend);
  }
  l34:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "func_args", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l33:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "func_args", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_atom()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "atom"));
  {  int yypos48= yypos, yythunkpos48= yythunkpos;  if (!yy_var()) goto l49;  goto l48;
  l49:;	  yypos= yypos48; yythunkpos= yythunkpos48;  if (!yy_string()) goto l50;  goto l48;
  l50:;	  yypos= yypos48; yythunkpos= yythunkpos48;  if (!yy_integer()) goto l47;
  }
  l48:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "atom", yybuf+yypos));
  return 1;
  l47:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "atom", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "list"));  if (!yymatchChar('[')) goto l51;
  l52:;	
  {  int yypos53= yypos, yythunkpos53= yythunkpos;  if (!yy__()) goto l53;  goto l52;
  l53:;	  yypos= yypos53; yythunkpos= yythunkpos53;
  }  yyDo(yy_1_list, yybegin, yyend);
  l54:;	
  {  int yypos55= yypos, yythunkpos55= yythunkpos;  if (!yy_expr()) goto l55;  yyDo(yySet, -1, 0);
  l56:;	
  {  int yypos57= yypos, yythunkpos57= yythunkpos;  if (!yy_list_sep()) goto l57;  goto l56;
  l57:;	  yypos= yypos57; yythunkpos= yythunkpos57;
  }  yyDo(yy_2_list, yybegin, yyend);  goto l54;
  l55:;	  yypos= yypos55; yythunkpos= yythunkpos55;
  }  if (!yymatchChar(']')) goto l51;  yyDo(yy_3_list, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "list", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l51:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "list", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_func()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "func"));  if (!yy_func_args()) goto l58;  yyDo(yySet, -2, 0);  if (!yymatchChar('{')) goto l58;
  l59:;	
  {  int yypos60= yypos, yythunkpos60= yythunkpos;
  {  int yypos61= yypos, yythunkpos61= yythunkpos;  if (!yy__()) goto l62;  goto l61;
  l62:;	  yypos= yypos61; yythunkpos= yythunkpos61;  if (!yy___()) goto l60;
  }
  l61:;	  goto l59;
  l60:;	  yypos= yypos60; yythunkpos= yythunkpos60;
  }  yyDo(yy_1_func, yybegin, yyend);  if (!yy_lexpr()) goto l58;  yyDo(yySet, -1, 0);  yyDo(yy_2_func, yybegin, yyend);
  l63:;	
  {  int yypos64= yypos, yythunkpos64= yythunkpos;  if (!yy_lexpr()) goto l64;  yyDo(yySet, -1, 0);  yyDo(yy_2_func, yybegin, yyend);  goto l63;
  l64:;	  yypos= yypos64; yythunkpos= yythunkpos64;
  }
  l65:;	
  {  int yypos66= yypos, yythunkpos66= yythunkpos;  if (!yy__()) goto l66;  goto l65;
  l66:;	  yypos= yypos66; yythunkpos= yythunkpos66;
  }  if (!yymatchChar('}')) goto l58;  yyDo(yy_3_func, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "func", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l58:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "func", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eop()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eop"));  if (!yymatchChar('(')) goto l67;  if (!yy_op()) goto l67;  if (!yymatchChar(')')) goto l67;
  yyprintf((stderr, "  ok   %s @ %s\n", "eop", yybuf+yypos));
  return 1;
  l67:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eop", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_op()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "op"));  if (!yy_operand()) goto l68;  yyDo(yySet, -3, 0);  if (!yy__()) goto l68;
  l69:;	
  {  int yypos70= yypos, yythunkpos70= yythunkpos;  if (!yy__()) goto l70;  goto l69;
  l70:;	  yypos= yypos70; yythunkpos= yythunkpos70;
  }  if (!yy_symbol()) goto l68;  yyDo(yySet, -2, 0);  if (!yy__()) goto l68;
  l71:;	
  {  int yypos72= yypos, yythunkpos72= yythunkpos;  if (!yy__()) goto l72;  goto l71;
  l72:;	  yypos= yypos72; yythunkpos= yythunkpos72;
  }  if (!yy_operand()) goto l68;  yyDo(yySet, -1, 0);  yyDo(yy_1_op, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "op", yybuf+yypos));  yyDo(yyPop, 3, 0);
  return 1;
  l68:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "op", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ecall()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "ecall"));  if (!yymatchChar('(')) goto l73;  if (!yy_identifier()) goto l73;  yyDo(yySet, -2, 0);  yyDo(yy_1_ecall, yybegin, yyend);
  l74:;	
  {  int yypos75= yypos, yythunkpos75= yythunkpos;  if (!yy_arg_sep()) goto l75;  if (!yy_expr()) goto l75;  yyDo(yySet, -1, 0);  yyDo(yy_2_ecall, yybegin, yyend);  goto l74;
  l75:;	  yypos= yypos75; yythunkpos= yythunkpos75;
  }  if (!yymatchChar(')')) goto l73;  yyDo(yy_3_ecall, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "ecall", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l73:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ecall", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_arg_sep()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "arg_sep"));
  {  int yypos77= yypos, yythunkpos77= yythunkpos;  if (!yymatchChar(',')) goto l78;
  l79:;	
  {  int yypos80= yypos, yythunkpos80= yythunkpos;
  {  int yypos81= yypos, yythunkpos81= yythunkpos;  if (!yy__()) goto l82;  goto l81;
  l82:;	  yypos= yypos81; yythunkpos= yythunkpos81;  if (!yy___()) goto l80;
  }
  l81:;	  goto l79;
  l80:;	  yypos= yypos80; yythunkpos= yythunkpos80;
  }  goto l77;
  l78:;	  yypos= yypos77; yythunkpos= yythunkpos77;  if (!yy__()) goto l76;
  l83:;	
  {  int yypos84= yypos, yythunkpos84= yythunkpos;  if (!yy__()) goto l84;  goto l83;
  l84:;	  yypos= yypos84; yythunkpos= yythunkpos84;
  }
  }
  l77:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "arg_sep", yybuf+yypos));
  return 1;
  l76:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "arg_sep", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_symbol()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "symbol"));
  {  int yypos86= yypos, yythunkpos86= yythunkpos;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l87;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\320\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l87;
  l88:;	
  {  int yypos89= yypos, yythunkpos89= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\320\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l89;  goto l88;
  l89:;	  yypos= yypos89; yythunkpos= yythunkpos89;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l87;  yyDo(yy_1_symbol, yybegin, yyend);  goto l86;
  l87:;	  yypos= yypos86; yythunkpos= yythunkpos86;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l85;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\360\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l85;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\360\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l85;
  l90:;	
  {  int yypos91= yypos, yythunkpos91= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\360\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l91;  goto l90;
  l91:;	  yypos= yypos91; yythunkpos= yythunkpos91;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l85;  yyDo(yy_2_symbol, yybegin, yyend);
  }
  l86:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "symbol", yybuf+yypos));
  return 1;
  l85:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "symbol", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_identifier()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "identifier"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l92;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l92;
  l93:;	
  {  int yypos94= yypos, yythunkpos94= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\040\377\003\000\000\000\000\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l94;  goto l93;
  l94:;	  yypos= yypos94; yythunkpos= yythunkpos94;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l92;  yyDo(yy_1_identifier, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "identifier", yybuf+yypos));
  return 1;
  l92:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "identifier", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy___()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "__"));
  {  int yypos96= yypos, yythunkpos96= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l96;  goto l97;
  l96:;	  yypos= yypos96; yythunkpos= yythunkpos96;
  }
  l97:;	  if (!yymatchClass((unsigned char *)"\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l95;
  yyprintf((stderr, "  ok   %s @ %s\n", "__", yybuf+yypos));
  return 1;
  l95:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "__", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_expr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "expr"));
  {  int yypos99= yypos, yythunkpos99= yythunkpos;  if (!yy_op()) goto l100;  goto l99;
  l100:;	  yypos= yypos99; yythunkpos= yythunkpos99;  if (!yy_eop()) goto l101;  goto l99;
  l101:;	  yypos= yypos99; yythunkpos= yythunkpos99;  if (!yy_ecall()) goto l102;  goto l99;
  l102:;	  yypos= yypos99; yythunkpos= yythunkpos99;  if (!yy_func()) goto l103;  goto l99;
  l103:;	  yypos= yypos99; yythunkpos= yythunkpos99;  if (!yy_list()) goto l104;  goto l99;
  l104:;	  yypos= yypos99; yythunkpos= yythunkpos99;  if (!yy_atom()) goto l98;
  }
  l99:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "expr", yybuf+yypos));
  return 1;
  l98:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "expr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_assign()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "assign"));
  {  int yypos106= yypos, yythunkpos106= yythunkpos;  if (!yy_identifier()) goto l107;  yyDo(yySet, -2, 0);  goto l106;
  l107:;	  yypos= yypos106; yythunkpos= yythunkpos106;  if (!yy_symbol()) goto l105;  yyDo(yySet, -2, 0);
  }
  l106:;	  if (!yy__()) goto l105;
  l108:;	
  {  int yypos109= yypos, yythunkpos109= yythunkpos;  if (!yy__()) goto l109;  goto l108;
  l109:;	  yypos= yypos109; yythunkpos= yythunkpos109;
  }  if (!yymatchChar('=')) goto l105;  if (!yy__()) goto l105;
  l110:;	
  {  int yypos111= yypos, yythunkpos111= yythunkpos;  if (!yy__()) goto l111;  goto l110;
  l111:;	  yypos= yypos111; yythunkpos= yythunkpos111;
  }
  {  int yypos112= yypos, yythunkpos112= yythunkpos;  if (!yy_icall()) goto l113;  yyDo(yySet, -1, 0);  goto l112;
  l113:;	  yypos= yypos112; yythunkpos= yythunkpos112;  if (!yy_expr()) goto l105;  yyDo(yySet, -1, 0);
  }
  l112:;	  yyDo(yy_1_assign, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "assign", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l105:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "assign", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_icall()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "icall"));  if (!yy_identifier()) goto l114;  yyDo(yySet, -2, 0);  yyDo(yy_1_icall, yybegin, yyend);  if (!yy_arg_sep()) goto l114;  if (!yy_expr()) goto l114;  yyDo(yySet, -1, 0);  yyDo(yy_2_icall, yybegin, yyend);
  l115:;	
  {  int yypos116= yypos, yythunkpos116= yythunkpos;  if (!yy_arg_sep()) goto l116;  if (!yy_expr()) goto l116;  yyDo(yySet, -1, 0);  yyDo(yy_2_icall, yybegin, yyend);  goto l115;
  l116:;	  yypos= yypos116; yythunkpos= yythunkpos116;
  }  yyDo(yy_3_icall, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "icall", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l114:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "icall", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_comment()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "comment"));
  l118:;	
  {  int yypos119= yypos, yythunkpos119= yythunkpos;  if (!yy__()) goto l119;  goto l118;
  l119:;	  yypos= yypos119; yythunkpos= yythunkpos119;
  }  if (!yymatchChar('#')) goto l117;
  l120:;	
  {  int yypos121= yypos, yythunkpos121= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\333\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l121;  goto l120;
  l121:;	  yypos= yypos121; yythunkpos= yythunkpos121;
  }
  {  int yypos122= yypos, yythunkpos122= yythunkpos;  if (!yy___()) goto l122;  goto l123;
  l122:;	  yypos= yypos122; yythunkpos= yythunkpos122;
  }
  l123:;	  yyDo(yy_1_comment, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "comment", yybuf+yypos));
  return 1;
  l117:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "comment", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_empty_line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "empty_line"));
  l125:;	
  {  int yypos126= yypos, yythunkpos126= yythunkpos;  if (!yy__()) goto l126;  goto l125;
  l126:;	  yypos= yypos126; yythunkpos= yythunkpos126;
  }  if (!yy___()) goto l124;  yyDo(yy_1_empty_line, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "empty_line", yybuf+yypos));
  return 1;
  l124:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "empty_line", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy__()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "_"));  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l127;
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yybuf+yypos));
  return 1;
  l127:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "_", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bad()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bad"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l128;  if (!yymatchDot()) goto l128;
  l129:;	
  {  int yypos130= yypos, yythunkpos130= yythunkpos;  if (!yymatchDot()) goto l130;  goto l129;
  l130:;	  yypos= yypos130; yythunkpos= yythunkpos130;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l128;  yyDo(yy_1_bad, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bad", yybuf+yypos));
  return 1;
  l128:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bad", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eof()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eof"));
  {  int yypos132= yypos, yythunkpos132= yythunkpos;  if (!yymatchDot()) goto l132;  goto l131;
  l132:;	  yypos= yypos132; yythunkpos= yythunkpos132;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "eof", yybuf+yypos));
  return 1;
  l131:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eof", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_lexpr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "lexpr"));
  l134:;	
  {  int yypos135= yypos, yythunkpos135= yythunkpos;  if (!yy__()) goto l135;  goto l134;
  l135:;	  yypos= yypos135; yythunkpos= yythunkpos135;
  }
  {  int yypos136= yypos, yythunkpos136= yythunkpos;  if (!yy_empty_line()) goto l137;  goto l136;
  l137:;	  yypos= yypos136; yythunkpos= yythunkpos136;  if (!yy_comment()) goto l138;  goto l136;
  l138:;	  yypos= yypos136; yythunkpos= yythunkpos136;  if (!yy_icall()) goto l139;  goto l136;
  l139:;	  yypos= yypos136; yythunkpos= yythunkpos136;  if (!yy_assign()) goto l140;  goto l136;
  l140:;	  yypos= yypos136; yythunkpos= yythunkpos136;  if (!yy_expr()) goto l133;
  }
  l136:;	
  l141:;	
  {  int yypos142= yypos, yythunkpos142= yythunkpos;  if (!yy__()) goto l142;  goto l141;
  l142:;	  yypos= yypos142; yythunkpos= yythunkpos142;
  }
  {  int yypos143= yypos, yythunkpos143= yythunkpos;  if (!yy___()) goto l143;  goto l144;
  l143:;	  yypos= yypos143; yythunkpos= yythunkpos143;
  }
  l144:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "lexpr", yybuf+yypos));
  return 1;
  l133:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "lexpr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_body()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "body"));
  {  int yypos146= yypos, yythunkpos146= yythunkpos;  if (!yy_lexpr()) goto l147;  yyDo(yySet, -1, 0);  yyDo(yy_1_body, yybegin, yyend);
  l148:;	
  {  int yypos149= yypos, yythunkpos149= yythunkpos;  if (!yy_lexpr()) goto l149;  yyDo(yySet, -1, 0);  yyDo(yy_1_body, yybegin, yyend);  goto l148;
  l149:;	  yypos= yypos149; yythunkpos= yythunkpos149;
  }  if (!yy_eof()) goto l147;  goto l146;
  l147:;	  yypos= yypos146; yythunkpos= yythunkpos146;
  l150:;	
  {  int yypos151= yypos, yythunkpos151= yythunkpos;  if (!yy_lexpr()) goto l151;  goto l150;
  l151:;	  yypos= yypos151; yythunkpos= yythunkpos151;
  }  if (!yy_bad()) goto l145;  if (!yy_eof()) goto l145;
  }
  l146:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "body", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l145:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "body", yybuf+yypos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= malloc(yybuflen);
      yytextlen= 1024;
      yytext= malloc(yytextlen);
      yythunkslen= 32;
      yythunks= malloc(sizeof(yythunk) * yythunkslen);
      yyvalslen= 32;
      yyvals= malloc(sizeof(YYSTYPE) * yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_body);
}

#endif


void l_stack_push() {
  if(++l_stackp == STACK_LEN) exit(1);
  l_stack_count[l_stackp] = 0;
}

void l_stack_add(LNode *n) {
  l_stack[l_stackp][l_stack_count[l_stackp]++] = n;
}

LNode **l_stack_pop() {
  int i;
  LNode **args = malloc(sizeof(LNode*) * l_stack_count[l_stackp]);
  for(i=0; i<l_stack_count[l_stackp]; i++) args[i] = l_stack[l_stackp][i];
  l_stackp--;
  return args;
}

char *yytos(char *yytext, int yyleng) {
  char *s = malloc(sizeof(char) * (yyleng + 1));
  strcpy(s, "");
  strncat(s, yytext, yyleng);
  return s;
}

LNode *l_create_int_node(char *yytext, int yyleng) {
  LNode *n = malloc(sizeof(LNode));
  n->type = L_NUM_TYPE;
  n->val = yytos(yytext, yyleng);
  return n;
}

LNode *l_create_str_node(char *yytext, int yyleng) {
  LNode *n = malloc(sizeof(LNode));
  n->type = L_STR_TYPE;
  n->val = yytos(yytext, yyleng);
  return n;
}

LNode *l_create_var_node(char *name) {
  LNode *n = malloc(sizeof(LNode));
  n->type = L_VAR_TYPE;
  n->val = name;
  return n;
}

LNode *l_create_assign_node(char *name, LNode *expr) {
  LNode *n = malloc(sizeof(LNode));
  n->type = L_ASSIGN_TYPE;
  n->val = name;
  n->exprc = 1;
  n->exprs = malloc(sizeof(LNode*));
  n->exprs[0] = expr;
  return n;
}

LNode *l_create_call_node(char *name, int argc, LNode **args) {
  LNode *n = malloc(sizeof(LNode));
  n->type = L_CALL_TYPE;
  n->val = name;
  n->exprc = argc;
  n->exprs = args;
  return n;
}

LNode *l_create_list_node(int itemc, LNode **items) {
  LNode *n = malloc(sizeof(LNode));
  n->type = L_LIST_TYPE;
  n->exprc = itemc;
  n->exprs = items;
  return n;
}

LNode *l_create_func_node(LNode *args, int exprc, LNode **exprs) {
  LNode *n = malloc(sizeof(LNode));
  n->type = L_FUNC_TYPE;
  LNode *exprsNode = malloc(sizeof(LNode));
  exprsNode->type = L_LIST_TYPE;
  exprsNode->exprc = exprc;
  exprsNode->exprs = exprs;
  n->exprc = 2;
  n->exprs = malloc(sizeof(LNode*) * 2);
  n->exprs[0] = args;
  n->exprs[1] = exprsNode;
  return n;
}

LNode *l_create_err_node(char *error) {
  LNode *n = malloc(sizeof(LNode));
  n->type = L_ERR_TYPE;
  n->val = error;
  return n;
}

// borrowed from O'Reilly book "lex & yacc" pg. 157
int yy_input(char *buf, int max_size) {
  int len = strlen(yy_input_ptr);
  int n = max_size < len ? max_size : len;
  if(n > 0) {
    memcpy(buf, yy_input_ptr, n);
    yy_input_ptr += n;
  }
  return n;
}

LAst *l_parse(const char *source) {
  L_AST = NULL;
  yy_input_ptr = source;
  yy_input_len = strlen(yy_input_ptr);
  while (yyparse());
  return L_AST;
}

