/* A recursive-descent parser generated by peg 0.1.7 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 35

#include "lydia.h"
int l_stackp = 0;
int l_line_no;
char *l_source_file;

#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      yybuflen *= 2;
      yybuf= realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if ((unsigned char)yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yybuf+yypos));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= (unsigned char)yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yybuf+yypos));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end)
{
  while (yythunkpos >= yythunkslen)
    {
      yythunkslen *= 2;
      yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng + 1))
	{
	  yytextlen *= 2;
	  yytext= realloc(yytext, yytextlen);
	}
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_alpha(); /* 35 */
YY_RULE(int) yy_digit(); /* 34 */
YY_RULE(int) yy_sym(); /* 33 */
YY_RULE(int) yy_sym_eq(); /* 32 */
YY_RULE(int) yy_esc(); /* 31 */
YY_RULE(int) yy_nsq(); /* 30 */
YY_RULE(int) yy_ndq(); /* 29 */
YY_RULE(int) yy_sq(); /* 28 */
YY_RULE(int) yy_dq(); /* 27 */
YY_RULE(int) yy_list_sep(); /* 26 */
YY_RULE(int) yy_integer(); /* 25 */
YY_RULE(int) yy_string(); /* 24 */
YY_RULE(int) yy_var(); /* 23 */
YY_RULE(int) yy_operand(); /* 22 */
YY_RULE(int) yy_func_args(); /* 21 */
YY_RULE(int) yy_atom(); /* 20 */
YY_RULE(int) yy_list(); /* 19 */
YY_RULE(int) yy_func(); /* 18 */
YY_RULE(int) yy_eop(); /* 17 */
YY_RULE(int) yy_op(); /* 16 */
YY_RULE(int) yy_ecall(); /* 15 */
YY_RULE(int) yy_arg_sep(); /* 14 */
YY_RULE(int) yy_symbol(); /* 13 */
YY_RULE(int) yy_identifier(); /* 12 */
YY_RULE(int) yy___(); /* 11 */
YY_RULE(int) yy_expr(); /* 10 */
YY_RULE(int) yy_assign(); /* 9 */
YY_RULE(int) yy_icall(); /* 8 */
YY_RULE(int) yy_comment(); /* 7 */
YY_RULE(int) yy_empty_line(); /* 6 */
YY_RULE(int) yy__(); /* 5 */
YY_RULE(int) yy_bad(); /* 4 */
YY_RULE(int) yy_eof(); /* 3 */
YY_RULE(int) yy_lexpr(); /* 2 */
YY_RULE(int) yy_body(); /* 1 */

YY_ACTION(void) yy_1___(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1___\n"));
   l_line_no++; ;
}
YY_ACTION(void) yy_1_integer(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_integer\n"));
   yy = l_create_num_node(yytos(yytext, yyleng)); ;
}
YY_ACTION(void) yy_1_identifier(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_identifier\n"));
   yy = yytos(yytext, yyleng); ;
}
YY_ACTION(void) yy_2_symbol(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_symbol\n"));
   yy = yytos(yytext, yyleng); ;
}
YY_ACTION(void) yy_1_symbol(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_symbol\n"));
   yy = yytos(yytext, yyleng); ;
}
YY_ACTION(void) yy_1_comment(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_comment\n"));
   yy = 0; ;
}
YY_ACTION(void) yy_1_empty_line(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_empty_line\n"));
   yy = 0; ;
}
YY_ACTION(void) yy_2_string(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_string\n"));
   yy = l_create_str_node(yytos(yytext, yyleng)); ;
}
YY_ACTION(void) yy_1_string(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_string\n"));
   yy = l_create_str_node(yytos(yytext, yyleng)); ;
}
YY_ACTION(void) yy_1_var(char *yytext, int yyleng)
{
#define name yyval[-1]
  yyprintf((stderr, "do yy_1_var\n"));
   yy = l_create_var_node(name); ;
#undef name
}
YY_ACTION(void) yy_3_list(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_3_list\n"));
   int count = l_stack_count[l_stackp];
                                                     yy = l_create_list_node(count, l_stack_pop()); ;
#undef e
}
YY_ACTION(void) yy_2_list(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_2_list\n"));
   l_stack_add(e); ;
#undef e
}
YY_ACTION(void) yy_1_list(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_1_list\n"));
   l_stack_push(); ;
#undef e
}
YY_ACTION(void) yy_1_op(char *yytext, int yyleng)
{
#define right yyval[-1]
#define symbol yyval[-2]
#define left yyval[-3]
  yyprintf((stderr, "do yy_1_op\n"));
   LNode **args = GC_MALLOC(sizeof(LNode*) * 2);
                                                     args[0] = left;
                                                     args[1] = right;
                                                     yy = l_create_call_node(symbol, 2, args); ;
#undef right
#undef symbol
#undef left
}
YY_ACTION(void) yy_4_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_4_func_args\n"));
   yy = l_create_list_node(0, NULL); ;
#undef arg
}
YY_ACTION(void) yy_3_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_3_func_args\n"));
   int count = l_stack_count[l_stackp];
                                                     yy = l_create_list_node(count, l_stack_pop()); ;
#undef arg
}
YY_ACTION(void) yy_2_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_2_func_args\n"));
   l_stack_add(l_create_var_node(arg)); ;
#undef arg
}
YY_ACTION(void) yy_1_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_1_func_args\n"));
   l_stack_push(); ;
#undef arg
}
YY_ACTION(void) yy_3_func(char *yytext, int yyleng)
{
#define e yyval[-1]
#define args yyval[-2]
  yyprintf((stderr, "do yy_3_func\n"));
   int count = l_stack_count[l_stackp];
                                                     yy = l_create_func_node(args, count, l_stack_pop()); ;
#undef e
#undef args
}
YY_ACTION(void) yy_2_func(char *yytext, int yyleng)
{
#define e yyval[-1]
#define args yyval[-2]
  yyprintf((stderr, "do yy_2_func\n"));
   if(e) l_stack_add(e); ;
#undef e
#undef args
}
YY_ACTION(void) yy_1_func(char *yytext, int yyleng)
{
#define e yyval[-1]
#define args yyval[-2]
  yyprintf((stderr, "do yy_1_func\n"));
   l_stack_push(); ;
#undef e
#undef args
}
YY_ACTION(void) yy_3_ecall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_3_ecall\n"));
   int count = l_stack_count[l_stackp];
                                                     yy = l_create_call_node(name, count, l_stack_pop()); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_2_ecall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_2_ecall\n"));
   l_stack_add(arg); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_1_ecall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_1_ecall\n"));
   l_stack_push(); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_3_icall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_3_icall\n"));
   int count = l_stack_count[l_stackp];
                                                     yy = l_create_call_node(name, count, l_stack_pop()); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_2_icall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_2_icall\n"));
   l_stack_add(arg); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_1_icall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_1_icall\n"));
   l_stack_push(); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_1_assign(char *yytext, int yyleng)
{
#define val yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_1_assign\n"));
   yy = l_create_assign_node(name, val); ;
#undef val
#undef name
}
YY_ACTION(void) yy_1_bad(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bad\n"));
   l_ast_add_node(l_create_err_node(yytos(yytext, yyleng), l_line_no)); ;
}
YY_ACTION(void) yy_1_body(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_1_body\n"));
   if(e) { l_ast_add_node(e); } ;
#undef e
}

YY_RULE(int) yy_alpha()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "alpha"));  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "alpha", yybuf+yypos));
  return 1;
  l1:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "alpha", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_digit()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "digit"));  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l2;
  yyprintf((stderr, "  ok   %s @ %s\n", "digit", yybuf+yypos));
  return 1;
  l2:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "digit", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_sym()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "sym"));  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\354\000\324\001\000\000\300\000\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l3;
  yyprintf((stderr, "  ok   %s @ %s\n", "sym", yybuf+yypos));
  return 1;
  l3:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sym", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_sym_eq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "sym_eq"));  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\354\000\364\001\000\000\300\000\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l4;
  yyprintf((stderr, "  ok   %s @ %s\n", "sym_eq", yybuf+yypos));
  return 1;
  l4:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sym_eq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_esc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "esc"));  if (!yymatchChar('\\')) goto l5;  if (!yymatchDot()) goto l5;
  yyprintf((stderr, "  ok   %s @ %s\n", "esc", yybuf+yypos));
  return 1;
  l5:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "esc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_nsq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "nsq"));
  {  int yypos7= yypos, yythunkpos7= yythunkpos;  if (!yy_sq()) goto l7;  goto l6;
  l7:;	  yypos= yypos7; yythunkpos= yythunkpos7;
  }  if (!yymatchDot()) goto l6;
  yyprintf((stderr, "  ok   %s @ %s\n", "nsq", yybuf+yypos));
  return 1;
  l6:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "nsq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ndq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "ndq"));
  {  int yypos9= yypos, yythunkpos9= yythunkpos;  if (!yy_dq()) goto l9;  goto l8;
  l9:;	  yypos= yypos9; yythunkpos= yythunkpos9;
  }  if (!yymatchDot()) goto l8;
  yyprintf((stderr, "  ok   %s @ %s\n", "ndq", yybuf+yypos));
  return 1;
  l8:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ndq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_sq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "sq"));  if (!yymatchChar('\'')) goto l10;
  yyprintf((stderr, "  ok   %s @ %s\n", "sq", yybuf+yypos));
  return 1;
  l10:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_dq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "dq"));  if (!yymatchChar('\"')) goto l11;
  yyprintf((stderr, "  ok   %s @ %s\n", "dq", yybuf+yypos));
  return 1;
  l11:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "dq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_list_sep()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "list_sep"));
  {  int yypos13= yypos, yythunkpos13= yythunkpos;  if (!yy__()) goto l14;  goto l13;
  l14:;	  yypos= yypos13; yythunkpos= yythunkpos13;  if (!yy___()) goto l15;  goto l13;
  l15:;	  yypos= yypos13; yythunkpos= yythunkpos13;  if (!yymatchChar(',')) goto l12;
  }
  l13:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "list_sep", yybuf+yypos));
  return 1;
  l12:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "list_sep", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_integer()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "integer"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l16;  if (!yy_digit()) goto l16;
  l17:;	
  {  int yypos18= yypos, yythunkpos18= yythunkpos;  if (!yy_digit()) goto l18;  goto l17;
  l18:;	  yypos= yypos18; yythunkpos= yythunkpos18;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l16;  yyDo(yy_1_integer, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "integer", yybuf+yypos));
  return 1;
  l16:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "integer", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_string()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "string"));
  {  int yypos20= yypos, yythunkpos20= yythunkpos;  if (!yy_dq()) goto l21;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l21;
  l22:;	
  {  int yypos23= yypos, yythunkpos23= yythunkpos;
  {  int yypos24= yypos, yythunkpos24= yythunkpos;  if (!yy_esc()) goto l25;  goto l24;
  l25:;	  yypos= yypos24; yythunkpos= yythunkpos24;  if (!yy_ndq()) goto l23;
  }
  l24:;	  goto l22;
  l23:;	  yypos= yypos23; yythunkpos= yythunkpos23;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l21;  if (!yy_dq()) goto l21;  yyDo(yy_1_string, yybegin, yyend);  goto l20;
  l21:;	  yypos= yypos20; yythunkpos= yythunkpos20;  if (!yy_sq()) goto l19;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l19;
  l26:;	
  {  int yypos27= yypos, yythunkpos27= yythunkpos;
  {  int yypos28= yypos, yythunkpos28= yythunkpos;  if (!yy_esc()) goto l29;  goto l28;
  l29:;	  yypos= yypos28; yythunkpos= yythunkpos28;  if (!yy_nsq()) goto l27;
  }
  l28:;	  goto l26;
  l27:;	  yypos= yypos27; yythunkpos= yythunkpos27;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l19;  if (!yy_sq()) goto l19;  yyDo(yy_2_string, yybegin, yyend);
  }
  l20:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "string", yybuf+yypos));
  return 1;
  l19:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "string", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_var()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "var"));  if (!yy_identifier()) goto l30;  yyDo(yySet, -1, 0);  yyDo(yy_1_var, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "var", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l30:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "var", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_operand()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "operand"));
  {  int yypos32= yypos, yythunkpos32= yythunkpos;  if (!yy_list()) goto l33;  goto l32;
  l33:;	  yypos= yypos32; yythunkpos= yythunkpos32;  if (!yy_atom()) goto l34;  goto l32;
  l34:;	  yypos= yypos32; yythunkpos= yythunkpos32;  if (!yy_eop()) goto l35;  goto l32;
  l35:;	  yypos= yypos32; yythunkpos= yythunkpos32;  if (!yy_ecall()) goto l31;
  }
  l32:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "operand", yybuf+yypos));
  return 1;
  l31:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "operand", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_func_args()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "func_args"));
  {  int yypos37= yypos, yythunkpos37= yythunkpos;  if (!yymatchChar('[')) goto l38;  yyDo(yy_1_func_args, yybegin, yyend);
  l41:;	
  {  int yypos42= yypos, yythunkpos42= yythunkpos;  if (!yy__()) goto l42;  goto l41;
  l42:;	  yypos= yypos42; yythunkpos= yythunkpos42;
  }  if (!yy_identifier()) goto l38;  yyDo(yySet, -1, 0);  yyDo(yy_2_func_args, yybegin, yyend);
  l39:;	
  {  int yypos40= yypos, yythunkpos40= yythunkpos;
  l43:;	
  {  int yypos44= yypos, yythunkpos44= yythunkpos;  if (!yy__()) goto l44;  goto l43;
  l44:;	  yypos= yypos44; yythunkpos= yythunkpos44;
  }  if (!yy_identifier()) goto l40;  yyDo(yySet, -1, 0);  yyDo(yy_2_func_args, yybegin, yyend);  goto l39;
  l40:;	  yypos= yypos40; yythunkpos= yythunkpos40;
  }
  l45:;	
  {  int yypos46= yypos, yythunkpos46= yythunkpos;  if (!yy__()) goto l46;  goto l45;
  l46:;	  yypos= yypos46; yythunkpos= yythunkpos46;
  }  if (!yymatchChar(']')) goto l38;
  l47:;	
  {  int yypos48= yypos, yythunkpos48= yythunkpos;  if (!yy__()) goto l48;  goto l47;
  l48:;	  yypos= yypos48; yythunkpos= yythunkpos48;
  }  yyDo(yy_3_func_args, yybegin, yyend);  goto l37;
  l38:;	  yypos= yypos37; yythunkpos= yythunkpos37;
  {  int yypos49= yypos, yythunkpos49= yythunkpos;  if (!yymatchChar('{')) goto l36;  yypos= yypos49; yythunkpos= yythunkpos49;
  }  yyDo(yy_4_func_args, yybegin, yyend);
  }
  l37:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "func_args", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l36:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "func_args", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_atom()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "atom"));
  {  int yypos51= yypos, yythunkpos51= yythunkpos;  if (!yy_var()) goto l52;  goto l51;
  l52:;	  yypos= yypos51; yythunkpos= yythunkpos51;  if (!yy_string()) goto l53;  goto l51;
  l53:;	  yypos= yypos51; yythunkpos= yythunkpos51;  if (!yy_integer()) goto l50;
  }
  l51:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "atom", yybuf+yypos));
  return 1;
  l50:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "atom", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "list"));  if (!yymatchChar('[')) goto l54;
  l55:;	
  {  int yypos56= yypos, yythunkpos56= yythunkpos;  if (!yy__()) goto l56;  goto l55;
  l56:;	  yypos= yypos56; yythunkpos= yythunkpos56;
  }  yyDo(yy_1_list, yybegin, yyend);
  l57:;	
  {  int yypos58= yypos, yythunkpos58= yythunkpos;  if (!yy_expr()) goto l58;  yyDo(yySet, -1, 0);
  l59:;	
  {  int yypos60= yypos, yythunkpos60= yythunkpos;  if (!yy_list_sep()) goto l60;  goto l59;
  l60:;	  yypos= yypos60; yythunkpos= yythunkpos60;
  }  yyDo(yy_2_list, yybegin, yyend);  goto l57;
  l58:;	  yypos= yypos58; yythunkpos= yythunkpos58;
  }  if (!yymatchChar(']')) goto l54;  yyDo(yy_3_list, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "list", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l54:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "list", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_func()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "func"));  if (!yy_func_args()) goto l61;  yyDo(yySet, -2, 0);  if (!yymatchChar('{')) goto l61;
  l62:;	
  {  int yypos63= yypos, yythunkpos63= yythunkpos;
  {  int yypos64= yypos, yythunkpos64= yythunkpos;  if (!yy__()) goto l65;  goto l64;
  l65:;	  yypos= yypos64; yythunkpos= yythunkpos64;  if (!yy___()) goto l63;
  }
  l64:;	  goto l62;
  l63:;	  yypos= yypos63; yythunkpos= yythunkpos63;
  }  yyDo(yy_1_func, yybegin, yyend);  if (!yy_lexpr()) goto l61;  yyDo(yySet, -1, 0);  yyDo(yy_2_func, yybegin, yyend);
  l66:;	
  {  int yypos67= yypos, yythunkpos67= yythunkpos;  if (!yy_lexpr()) goto l67;  yyDo(yySet, -1, 0);  yyDo(yy_2_func, yybegin, yyend);  goto l66;
  l67:;	  yypos= yypos67; yythunkpos= yythunkpos67;
  }
  l68:;	
  {  int yypos69= yypos, yythunkpos69= yythunkpos;  if (!yy__()) goto l69;  goto l68;
  l69:;	  yypos= yypos69; yythunkpos= yythunkpos69;
  }  if (!yymatchChar('}')) goto l61;  yyDo(yy_3_func, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "func", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l61:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "func", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eop()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eop"));  if (!yymatchChar('(')) goto l70;  if (!yy_op()) goto l70;  if (!yymatchChar(')')) goto l70;
  yyprintf((stderr, "  ok   %s @ %s\n", "eop", yybuf+yypos));
  return 1;
  l70:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eop", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_op()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "op"));  if (!yy_operand()) goto l71;  yyDo(yySet, -3, 0);  if (!yy__()) goto l71;
  l72:;	
  {  int yypos73= yypos, yythunkpos73= yythunkpos;  if (!yy__()) goto l73;  goto l72;
  l73:;	  yypos= yypos73; yythunkpos= yythunkpos73;
  }  if (!yy_symbol()) goto l71;  yyDo(yySet, -2, 0);  if (!yy__()) goto l71;
  l74:;	
  {  int yypos75= yypos, yythunkpos75= yythunkpos;  if (!yy__()) goto l75;  goto l74;
  l75:;	  yypos= yypos75; yythunkpos= yythunkpos75;
  }  if (!yy_operand()) goto l71;  yyDo(yySet, -1, 0);  yyDo(yy_1_op, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "op", yybuf+yypos));  yyDo(yyPop, 3, 0);
  return 1;
  l71:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "op", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ecall()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "ecall"));  if (!yymatchChar('(')) goto l76;  if (!yy_identifier()) goto l76;  yyDo(yySet, -2, 0);  yyDo(yy_1_ecall, yybegin, yyend);
  l77:;	
  {  int yypos78= yypos, yythunkpos78= yythunkpos;  if (!yy_arg_sep()) goto l78;  if (!yy_expr()) goto l78;  yyDo(yySet, -1, 0);  yyDo(yy_2_ecall, yybegin, yyend);  goto l77;
  l78:;	  yypos= yypos78; yythunkpos= yythunkpos78;
  }  if (!yymatchChar(')')) goto l76;  yyDo(yy_3_ecall, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "ecall", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l76:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ecall", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_arg_sep()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "arg_sep"));
  {  int yypos80= yypos, yythunkpos80= yythunkpos;  if (!yymatchChar(',')) goto l81;
  l82:;	
  {  int yypos83= yypos, yythunkpos83= yythunkpos;
  {  int yypos84= yypos, yythunkpos84= yythunkpos;  if (!yy__()) goto l85;  goto l84;
  l85:;	  yypos= yypos84; yythunkpos= yythunkpos84;  if (!yy___()) goto l83;
  }
  l84:;	  goto l82;
  l83:;	  yypos= yypos83; yythunkpos= yythunkpos83;
  }  goto l80;
  l81:;	  yypos= yypos80; yythunkpos= yythunkpos80;  if (!yy__()) goto l79;
  l86:;	
  {  int yypos87= yypos, yythunkpos87= yythunkpos;  if (!yy__()) goto l87;  goto l86;
  l87:;	  yypos= yypos87; yythunkpos= yythunkpos87;
  }
  }
  l80:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "arg_sep", yybuf+yypos));
  return 1;
  l79:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "arg_sep", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_symbol()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "symbol"));
  {  int yypos89= yypos, yythunkpos89= yythunkpos;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l90;  if (!yy_sym_eq()) goto l90;  if (!yy_sym_eq()) goto l90;
  l91:;	
  {  int yypos92= yypos, yythunkpos92= yythunkpos;  if (!yy_sym_eq()) goto l92;  goto l91;
  l92:;	  yypos= yypos92; yythunkpos= yythunkpos92;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l90;  yyDo(yy_1_symbol, yybegin, yyend);  goto l89;
  l90:;	  yypos= yypos89; yythunkpos= yythunkpos89;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l88;  if (!yy_sym()) goto l88;
  l93:;	
  {  int yypos94= yypos, yythunkpos94= yythunkpos;  if (!yy_sym()) goto l94;  goto l93;
  l94:;	  yypos= yypos94; yythunkpos= yythunkpos94;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l88;  yyDo(yy_2_symbol, yybegin, yyend);
  }
  l89:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "symbol", yybuf+yypos));
  return 1;
  l88:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "symbol", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_identifier()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "identifier"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l95;
  l96:;	
  {  int yypos97= yypos, yythunkpos97= yythunkpos;
  {  int yypos98= yypos, yythunkpos98= yythunkpos;  if (!yy_sym_eq()) goto l99;  goto l98;
  l99:;	  yypos= yypos98; yythunkpos= yythunkpos98;  if (!yy_digit()) goto l97;
  }
  l98:;	  goto l96;
  l97:;	  yypos= yypos97; yythunkpos= yythunkpos97;
  }  if (!yy_alpha()) goto l95;
  l100:;	
  {  int yypos101= yypos, yythunkpos101= yythunkpos;
  {  int yypos102= yypos, yythunkpos102= yythunkpos;  if (!yy_sym_eq()) goto l103;  goto l102;
  l103:;	  yypos= yypos102; yythunkpos= yythunkpos102;  if (!yy_digit()) goto l104;  goto l102;
  l104:;	  yypos= yypos102; yythunkpos= yythunkpos102;  if (!yy_alpha()) goto l101;
  }
  l102:;	  goto l100;
  l101:;	  yypos= yypos101; yythunkpos= yythunkpos101;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l95;  yyDo(yy_1_identifier, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "identifier", yybuf+yypos));
  return 1;
  l95:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "identifier", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy___()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "__"));
  {  int yypos106= yypos, yythunkpos106= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l106;  goto l107;
  l106:;	  yypos= yypos106; yythunkpos= yythunkpos106;
  }
  l107:;	  if (!yymatchClass((unsigned char *)"\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l105;  yyDo(yy_1___, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "__", yybuf+yypos));
  return 1;
  l105:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "__", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_expr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "expr"));
  {  int yypos109= yypos, yythunkpos109= yythunkpos;  if (!yy_op()) goto l110;  goto l109;
  l110:;	  yypos= yypos109; yythunkpos= yythunkpos109;  if (!yy_eop()) goto l111;  goto l109;
  l111:;	  yypos= yypos109; yythunkpos= yythunkpos109;  if (!yy_ecall()) goto l112;  goto l109;
  l112:;	  yypos= yypos109; yythunkpos= yythunkpos109;  if (!yy_func()) goto l113;  goto l109;
  l113:;	  yypos= yypos109; yythunkpos= yythunkpos109;  if (!yy_list()) goto l114;  goto l109;
  l114:;	  yypos= yypos109; yythunkpos= yythunkpos109;  if (!yy_atom()) goto l108;
  }
  l109:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "expr", yybuf+yypos));
  return 1;
  l108:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "expr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_assign()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "assign"));
  {  int yypos116= yypos, yythunkpos116= yythunkpos;  if (!yy_identifier()) goto l117;  yyDo(yySet, -2, 0);  goto l116;
  l117:;	  yypos= yypos116; yythunkpos= yythunkpos116;  if (!yy_symbol()) goto l115;  yyDo(yySet, -2, 0);
  }
  l116:;	  if (!yy__()) goto l115;
  l118:;	
  {  int yypos119= yypos, yythunkpos119= yythunkpos;  if (!yy__()) goto l119;  goto l118;
  l119:;	  yypos= yypos119; yythunkpos= yythunkpos119;
  }  if (!yymatchChar('=')) goto l115;  if (!yy__()) goto l115;
  l120:;	
  {  int yypos121= yypos, yythunkpos121= yythunkpos;  if (!yy__()) goto l121;  goto l120;
  l121:;	  yypos= yypos121; yythunkpos= yythunkpos121;
  }
  {  int yypos122= yypos, yythunkpos122= yythunkpos;  if (!yy_icall()) goto l123;  yyDo(yySet, -1, 0);  goto l122;
  l123:;	  yypos= yypos122; yythunkpos= yythunkpos122;  if (!yy_expr()) goto l115;  yyDo(yySet, -1, 0);
  }
  l122:;	  yyDo(yy_1_assign, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "assign", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l115:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "assign", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_icall()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "icall"));  if (!yy_identifier()) goto l124;  yyDo(yySet, -2, 0);  yyDo(yy_1_icall, yybegin, yyend);  if (!yy_arg_sep()) goto l124;  if (!yy_expr()) goto l124;  yyDo(yySet, -1, 0);  yyDo(yy_2_icall, yybegin, yyend);
  l125:;	
  {  int yypos126= yypos, yythunkpos126= yythunkpos;  if (!yy_arg_sep()) goto l126;  if (!yy_expr()) goto l126;  yyDo(yySet, -1, 0);  yyDo(yy_2_icall, yybegin, yyend);  goto l125;
  l126:;	  yypos= yypos126; yythunkpos= yythunkpos126;
  }  yyDo(yy_3_icall, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "icall", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l124:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "icall", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_comment()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "comment"));
  l128:;	
  {  int yypos129= yypos, yythunkpos129= yythunkpos;  if (!yy__()) goto l129;  goto l128;
  l129:;	  yypos= yypos129; yythunkpos= yythunkpos129;
  }  if (!yymatchChar('#')) goto l127;
  l130:;	
  {  int yypos131= yypos, yythunkpos131= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\333\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l131;  goto l130;
  l131:;	  yypos= yypos131; yythunkpos= yythunkpos131;
  }
  {  int yypos132= yypos, yythunkpos132= yythunkpos;  if (!yy___()) goto l132;  goto l133;
  l132:;	  yypos= yypos132; yythunkpos= yythunkpos132;
  }
  l133:;	  yyDo(yy_1_comment, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "comment", yybuf+yypos));
  return 1;
  l127:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "comment", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_empty_line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "empty_line"));
  l135:;	
  {  int yypos136= yypos, yythunkpos136= yythunkpos;  if (!yy__()) goto l136;  goto l135;
  l136:;	  yypos= yypos136; yythunkpos= yythunkpos136;
  }  if (!yy___()) goto l134;  yyDo(yy_1_empty_line, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "empty_line", yybuf+yypos));
  return 1;
  l134:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "empty_line", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy__()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "_"));  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l137;
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yybuf+yypos));
  return 1;
  l137:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "_", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bad()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bad"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l138;  if (!yymatchDot()) goto l138;
  l139:;	
  {  int yypos140= yypos, yythunkpos140= yythunkpos;  if (!yymatchDot()) goto l140;  goto l139;
  l140:;	  yypos= yypos140; yythunkpos= yythunkpos140;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l138;  yyDo(yy_1_bad, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bad", yybuf+yypos));
  return 1;
  l138:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bad", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eof()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eof"));
  {  int yypos142= yypos, yythunkpos142= yythunkpos;  if (!yymatchDot()) goto l142;  goto l141;
  l142:;	  yypos= yypos142; yythunkpos= yythunkpos142;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "eof", yybuf+yypos));
  return 1;
  l141:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eof", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_lexpr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "lexpr"));
  l144:;	
  {  int yypos145= yypos, yythunkpos145= yythunkpos;  if (!yy__()) goto l145;  goto l144;
  l145:;	  yypos= yypos145; yythunkpos= yythunkpos145;
  }
  {  int yypos146= yypos, yythunkpos146= yythunkpos;  if (!yy_empty_line()) goto l147;  goto l146;
  l147:;	  yypos= yypos146; yythunkpos= yythunkpos146;  if (!yy_comment()) goto l148;  goto l146;
  l148:;	  yypos= yypos146; yythunkpos= yythunkpos146;  if (!yy_icall()) goto l149;  goto l146;
  l149:;	  yypos= yypos146; yythunkpos= yythunkpos146;  if (!yy_assign()) goto l150;  goto l146;
  l150:;	  yypos= yypos146; yythunkpos= yythunkpos146;  if (!yy_expr()) goto l143;
  }
  l146:;	
  l151:;	
  {  int yypos152= yypos, yythunkpos152= yythunkpos;  if (!yy__()) goto l152;  goto l151;
  l152:;	  yypos= yypos152; yythunkpos= yythunkpos152;
  }
  {  int yypos153= yypos, yythunkpos153= yythunkpos;  if (!yy___()) goto l153;  goto l154;
  l153:;	  yypos= yypos153; yythunkpos= yythunkpos153;
  }
  l154:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "lexpr", yybuf+yypos));
  return 1;
  l143:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "lexpr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_body()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "body"));
  {  int yypos156= yypos, yythunkpos156= yythunkpos;  if (!yy_lexpr()) goto l157;  yyDo(yySet, -1, 0);  yyDo(yy_1_body, yybegin, yyend);
  l158:;	
  {  int yypos159= yypos, yythunkpos159= yythunkpos;  if (!yy_lexpr()) goto l159;  yyDo(yySet, -1, 0);  yyDo(yy_1_body, yybegin, yyend);  goto l158;
  l159:;	  yypos= yypos159; yythunkpos= yythunkpos159;
  }  if (!yy_eof()) goto l157;  goto l156;
  l157:;	  yypos= yypos156; yythunkpos= yythunkpos156;
  l160:;	
  {  int yypos161= yypos, yythunkpos161= yythunkpos;  if (!yy_lexpr()) goto l161;  goto l160;
  l161:;	  yypos= yypos161; yythunkpos= yythunkpos161;
  }  if (!yy_bad()) goto l155;  if (!yy_eof()) goto l155;
  }
  l156:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "body", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l155:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "body", yybuf+yypos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= malloc(yybuflen);
      yytextlen= 1024;
      yytext= malloc(yytextlen);
      yythunkslen= 32;
      yythunks= malloc(sizeof(yythunk) * yythunkslen);
      yyvalslen= 32;
      yyvals= malloc(sizeof(YYSTYPE) * yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_body);
}

#endif


void l_stack_push() {
  if(++l_stackp == STACK_LEN) exit(1);
  l_stack_count[l_stackp] = 0;
}

void l_stack_add(LNode *n) {
  l_stack[l_stackp][l_stack_count[l_stackp]++] = n;
}

LNode **l_stack_pop() {
  int i;
  LNode **args = GC_MALLOC(sizeof(LNode*) * l_stack_count[l_stackp]);
  for(i=0; i<l_stack_count[l_stackp]; i++) args[i] = l_stack[l_stackp][i];
  l_stackp--;
  return args;
}

char *yytos(char *yytext, int yyleng) {
  char *s = GC_MALLOC(sizeof(char) * (yyleng + 1));
  strcpy(s, "");
  strncat(s, yytext, yyleng);
  return s;
}

LNode *l_create_ast_node(enum LNodeType type) {
  LNode *n = GC_MALLOC(sizeof(LNode));
  n->type = type;
  n->line_no = l_line_no;
  n->source_file = GC_MALLOC(strlen(l_source_file) + 1);
  strcpy(n->source_file, l_source_file);
  return n;
}

LNode *l_create_num_node(char *num) {
  LNode *n = l_create_ast_node(L_NUM_TYPE);
  n->val = num;
  return n;
}

LNode *l_create_str_node(char *str) {
  LNode *n = l_create_ast_node(L_STR_TYPE);
  n->val = str;
  return n;
}

LNode *l_create_var_node(char *name) {
  LNode *n = l_create_ast_node(L_VAR_TYPE);
  n->val = name;
  return n;
}

LNode *l_create_assign_node(char *name, LNode *expr) {
  LNode *n = l_create_ast_node(L_ASSIGN_TYPE);
  n->val = name;
  n->exprc = 1;
  n->exprs = GC_MALLOC(sizeof(LNode*));
  n->exprs[0] = expr;
  return n;
}

LNode *l_create_call_node(char *name, int argc, LNode **args) {
  LNode *n = l_create_ast_node(L_CALL_TYPE);
  n->val = name;
  n->exprc = argc;
  n->exprs = args;
  return n;
}

LNode *l_create_list_node(int itemc, LNode **items) {
  LNode *n = l_create_ast_node(L_LIST_TYPE);
  n->exprc = itemc;
  n->exprs = items;
  return n;
}

LNode *l_create_func_node(LNode *args, int exprc, LNode **exprs) {
  LNode *n = l_create_ast_node(L_FUNC_TYPE);
  LNode *exprsNode = GC_MALLOC(sizeof(LNode));
  exprsNode->type = L_LIST_TYPE;
  exprsNode->exprc = exprc;
  exprsNode->exprs = exprs;
  n->exprc = 2;
  n->exprs = GC_MALLOC(sizeof(LNode*) * 2);
  n->exprs[0] = args;
  n->exprs[1] = exprsNode;
  return n;
}

LNode *l_create_err_node(char *error, int line) {
  LNode *n = l_create_ast_node(L_ERR_TYPE);
  char *buf = GC_MALLOC(sizeof(char) * 255);
  snprintf(buf, 254, "line %d: %s", line, error);
  n->val = buf;
  return n;
}

// borrowed from O'Reilly book "lex & yacc" pg. 157
int yy_input(char *buf, int max_size) {
  int len = strlen(yy_input_ptr);
  int n = max_size < len ? max_size : len;
  if(n > 0) {
    memcpy(buf, yy_input_ptr, n);
    yy_input_ptr += n;
  }
  return n;
}

LAst l_parse(const char *source, const char *source_file) {
  L_AST = create_list();
  l_source_file = source_file;
  l_line_no = 1;
  yy_input_ptr = source;
  yy_input_len = strlen(yy_input_ptr);
  while (yyparse());
  return L_AST;
}

