/* A recursive-descent parser generated by peg 0.1.2 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 34


#include <string.h>
#include <glib.h>

int yy_input(char *buf, int max_size);

#define YY_INPUT(b, r, ms) (r = yy_input(b, ms))

#define YYSTYPE node*

GSList* parse_ast;

#define STACK_LEN 1024

node* stack[STACK_LEN][MAX_ARG_COUNT];
int stack_argc[STACK_LEN];
int stackp = 0;
int argp = 0;
int i;

#define P_NEW(n, v)           malloc(sizeof(node*))
#define P_NEW2(n, v1, v2)     malloc(sizeof(node*))
#define P_NEW3(n, v1, v2, v3) malloc(sizeof(node*))
#define P_ADD(node)           (parse_ast = g_slist_append(parse_ast, node))

node* rb_str_new(char *, int);
node* rb_ary_new();

char* yytos(char *, int);

void stack_push();
void stack_add(node*);
node* stack_pop();

node* create_int_node(char*, int);
node* create_str_node(char*, int);
node* create_rng_node(node*, node*);
node* create_var_node(char*);
node* create_call_node(char*, int, node**);
node* create_err_node(char*, int);


#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      yybuflen *= 2;
      yybuf= realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if (yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yybuf+yypos));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yybuf+yypos));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end)
{
  while (yythunkpos >= yythunkslen)
    {
      yythunkslen *= 2;
      yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng - 1))
	{
	  yytextlen *= 2;
	  yytext= realloc(yytext, yytextlen);
	}
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_digit(); /* 34 */
YY_RULE(int) yy_esc(); /* 33 */
YY_RULE(int) yy_nsq(); /* 32 */
YY_RULE(int) yy_ndq(); /* 31 */
YY_RULE(int) yy_sq(); /* 30 */
YY_RULE(int) yy_dq(); /* 29 */
YY_RULE(int) yy_rangeop(); /* 28 */
YY_RULE(int) yy_list_sep(); /* 27 */
YY_RULE(int) yy_integer(); /* 26 */
YY_RULE(int) yy_range(); /* 25 */
YY_RULE(int) yy_string(); /* 24 */
YY_RULE(int) yy_var(); /* 23 */
YY_RULE(int) yy_operand(); /* 22 */
YY_RULE(int) yy_func_args(); /* 21 */
YY_RULE(int) yy_atom(); /* 20 */
YY_RULE(int) yy_list(); /* 19 */
YY_RULE(int) yy_func(); /* 18 */
YY_RULE(int) yy_eop(); /* 17 */
YY_RULE(int) yy_op(); /* 16 */
YY_RULE(int) yy_ecall(); /* 15 */
YY_RULE(int) yy_arg_sep(); /* 14 */
YY_RULE(int) yy_symbol(); /* 13 */
YY_RULE(int) yy_identifier(); /* 12 */
YY_RULE(int) yy___(); /* 11 */
YY_RULE(int) yy_expr(); /* 10 */
YY_RULE(int) yy_assign(); /* 9 */
YY_RULE(int) yy_icall(); /* 8 */
YY_RULE(int) yy_comment(); /* 7 */
YY_RULE(int) yy_empty_line(); /* 6 */
YY_RULE(int) yy__(); /* 5 */
YY_RULE(int) yy_bad(); /* 4 */
YY_RULE(int) yy_eof(); /* 3 */
YY_RULE(int) yy_lexpr(); /* 2 */
YY_RULE(int) yy_body(); /* 1 */

YY_ACTION(void) yy_1_integer(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_integer\n"));
   yy = create_int_node(yytext, yyleng); ;
}
YY_ACTION(void) yy_1_identifier(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_identifier\n"));
   yy = yytos(yytext, yyleng); ;
}
YY_ACTION(void) yy_2_symbol(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_symbol\n"));
   yy = yytos(yytext, yyleng); ;
}
YY_ACTION(void) yy_1_symbol(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_symbol\n"));
   yy = yytos(yytext, yyleng); ;
}
YY_ACTION(void) yy_1_comment(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_comment\n"));
   yy = 0; ;
}
YY_ACTION(void) yy_1_empty_line(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_empty_line\n"));
   yy = 0; ;
}
YY_ACTION(void) yy_2_string(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_string\n"));
   yy = create_str_node(yytext, yyleng); ;
}
YY_ACTION(void) yy_1_string(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_string\n"));
   yy = create_str_node(yytext, yyleng); ;
}
YY_ACTION(void) yy_1_var(char *yytext, int yyleng)
{
#define name yyval[-1]
  yyprintf((stderr, "do yy_1_var\n"));
   yy = create_var_node(name); ;
#undef name
}
YY_ACTION(void) yy_1_range(char *yytext, int yyleng)
{
#define last yyval[-1]
#define first yyval[-2]
  yyprintf((stderr, "do yy_1_range\n"));
   yy = create_rng_node(first, last); ;
#undef last
#undef first
}
YY_ACTION(void) yy_3_list(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_3_list\n"));
   yy = P_NEW("list", stack_pop()); ;
#undef e
}
YY_ACTION(void) yy_2_list(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_2_list\n"));
   stack_add(e); ;
#undef e
}
YY_ACTION(void) yy_1_list(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_1_list\n"));
   stack_push(); ;
#undef e
}
YY_ACTION(void) yy_1_op(char *yytext, int yyleng)
{
#define right yyval[-1]
#define symbol yyval[-2]
#define left yyval[-3]
  yyprintf((stderr, "do yy_1_op\n"));
   node** args = malloc(sizeof(node*) * 2);
                                                     args[0] = left;
                                                     args[1] = right;
                                                     yy = create_call_node(symbol, 2, args); ;
#undef right
#undef symbol
#undef left
}
YY_ACTION(void) yy_4_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_4_func_args\n"));
   yy = 0; ;
#undef arg
}
YY_ACTION(void) yy_3_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_3_func_args\n"));
   yy = stack_pop(); ;
#undef arg
}
YY_ACTION(void) yy_2_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_2_func_args\n"));
   stack_add(arg); ;
#undef arg
}
YY_ACTION(void) yy_1_func_args(char *yytext, int yyleng)
{
#define arg yyval[-1]
  yyprintf((stderr, "do yy_1_func_args\n"));
   stack_push(); ;
#undef arg
}
YY_ACTION(void) yy_3_func(char *yytext, int yyleng)
{
#define e yyval[-1]
#define args yyval[-2]
  yyprintf((stderr, "do yy_3_func\n"));
   yy = P_NEW2("func", args ? args : rb_ary_new(), stack_pop()); ;
#undef e
#undef args
}
YY_ACTION(void) yy_2_func(char *yytext, int yyleng)
{
#define e yyval[-1]
#define args yyval[-2]
  yyprintf((stderr, "do yy_2_func\n"));
   if(e) stack_add(e); ;
#undef e
#undef args
}
YY_ACTION(void) yy_1_func(char *yytext, int yyleng)
{
#define e yyval[-1]
#define args yyval[-2]
  yyprintf((stderr, "do yy_1_func\n"));
   stack_push(); ;
#undef e
#undef args
}
YY_ACTION(void) yy_3_ecall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_3_ecall\n"));
   yy = create_call_node(name, stack_argc[stackp], stack_pop()); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_2_ecall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_2_ecall\n"));
   stack_add(arg); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_1_ecall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_1_ecall\n"));
   stack_push(); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_3_icall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_3_icall\n"));
   yy = create_call_node(name, stack_argc[stackp], stack_pop()); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_2_icall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_2_icall\n"));
   stack_add(arg); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_1_icall(char *yytext, int yyleng)
{
#define arg yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_1_icall\n"));
   stack_push(); ;
#undef arg
#undef name
}
YY_ACTION(void) yy_1_assign(char *yytext, int yyleng)
{
#define val yyval[-1]
#define name yyval[-2]
  yyprintf((stderr, "do yy_1_assign\n"));
   yy = P_NEW2("assign", name, val); ;
#undef val
#undef name
}
YY_ACTION(void) yy_1_bad(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bad\n"));
   P_ADD(create_err_node(yytext, yyleng)); ;
}
YY_ACTION(void) yy_1_body(char *yytext, int yyleng)
{
#define e yyval[-1]
  yyprintf((stderr, "do yy_1_body\n"));
   e && P_ADD(e); ;
#undef e
}

YY_RULE(int) yy_digit()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "digit"));  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "digit", yybuf+yypos));
  return 1;
  l1:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "digit", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_esc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "esc"));  if (!yymatchChar('\\')) goto l2;  if (!yymatchDot()) goto l2;
  yyprintf((stderr, "  ok   %s @ %s\n", "esc", yybuf+yypos));
  return 1;
  l2:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "esc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_nsq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "nsq"));
  {  int yypos4= yypos, yythunkpos4= yythunkpos;  if (!yy_sq()) goto l4;  goto l3;
  l4:;	  yypos= yypos4; yythunkpos= yythunkpos4;
  }  if (!yymatchDot()) goto l3;
  yyprintf((stderr, "  ok   %s @ %s\n", "nsq", yybuf+yypos));
  return 1;
  l3:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "nsq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ndq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "ndq"));
  {  int yypos6= yypos, yythunkpos6= yythunkpos;  if (!yy_dq()) goto l6;  goto l5;
  l6:;	  yypos= yypos6; yythunkpos= yythunkpos6;
  }  if (!yymatchDot()) goto l5;
  yyprintf((stderr, "  ok   %s @ %s\n", "ndq", yybuf+yypos));
  return 1;
  l5:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ndq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_sq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "sq"));  if (!yymatchChar('\'')) goto l7;
  yyprintf((stderr, "  ok   %s @ %s\n", "sq", yybuf+yypos));
  return 1;
  l7:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_dq()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "dq"));  if (!yymatchChar('\"')) goto l8;
  yyprintf((stderr, "  ok   %s @ %s\n", "dq", yybuf+yypos));
  return 1;
  l8:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "dq", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_rangeop()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "rangeop"));
  {  int yypos10= yypos, yythunkpos10= yythunkpos;  if (!yy_var()) goto l11;  goto l10;
  l11:;	  yypos= yypos10; yythunkpos= yythunkpos10;  if (!yy_integer()) goto l12;  goto l10;
  l12:;	  yypos= yypos10; yythunkpos= yythunkpos10;  if (!yy_eop()) goto l13;  goto l10;
  l13:;	  yypos= yypos10; yythunkpos= yythunkpos10;  if (!yy_ecall()) goto l9;
  }
  l10:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "rangeop", yybuf+yypos));
  return 1;
  l9:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "rangeop", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_list_sep()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "list_sep"));
  {  int yypos15= yypos, yythunkpos15= yythunkpos;  if (!yy__()) goto l16;  goto l15;
  l16:;	  yypos= yypos15; yythunkpos= yythunkpos15;  if (!yy___()) goto l17;  goto l15;
  l17:;	  yypos= yypos15; yythunkpos= yythunkpos15;  if (!yymatchChar(',')) goto l14;
  }
  l15:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "list_sep", yybuf+yypos));
  return 1;
  l14:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "list_sep", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_integer()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "integer"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l18;  if (!yy_digit()) goto l18;
  l19:;	
  {  int yypos20= yypos, yythunkpos20= yythunkpos;  if (!yy_digit()) goto l20;  goto l19;
  l20:;	  yypos= yypos20; yythunkpos= yythunkpos20;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l18;  yyDo(yy_1_integer, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "integer", yybuf+yypos));
  return 1;
  l18:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "integer", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_range()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "range"));  if (!yy_rangeop()) goto l21;  yyDo(yySet, -2, 0);  if (!yymatchString("..")) goto l21;  if (!yy_rangeop()) goto l21;  yyDo(yySet, -1, 0);  yyDo(yy_1_range, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "range", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l21:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "range", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_string()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "string"));
  {  int yypos23= yypos, yythunkpos23= yythunkpos;  if (!yy_dq()) goto l24;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l24;
  l25:;	
  {  int yypos26= yypos, yythunkpos26= yythunkpos;
  {  int yypos27= yypos, yythunkpos27= yythunkpos;  if (!yy_esc()) goto l28;  goto l27;
  l28:;	  yypos= yypos27; yythunkpos= yythunkpos27;  if (!yy_ndq()) goto l26;
  }
  l27:;	  goto l25;
  l26:;	  yypos= yypos26; yythunkpos= yythunkpos26;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l24;  if (!yy_dq()) goto l24;  yyDo(yy_1_string, yybegin, yyend);  goto l23;
  l24:;	  yypos= yypos23; yythunkpos= yythunkpos23;  if (!yy_sq()) goto l22;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l22;
  l29:;	
  {  int yypos30= yypos, yythunkpos30= yythunkpos;
  {  int yypos31= yypos, yythunkpos31= yythunkpos;  if (!yy_esc()) goto l32;  goto l31;
  l32:;	  yypos= yypos31; yythunkpos= yythunkpos31;  if (!yy_nsq()) goto l30;
  }
  l31:;	  goto l29;
  l30:;	  yypos= yypos30; yythunkpos= yythunkpos30;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l22;  if (!yy_sq()) goto l22;  yyDo(yy_2_string, yybegin, yyend);
  }
  l23:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "string", yybuf+yypos));
  return 1;
  l22:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "string", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_var()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "var"));  if (!yy_identifier()) goto l33;  yyDo(yySet, -1, 0);  yyDo(yy_1_var, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "var", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l33:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "var", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_operand()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "operand"));
  {  int yypos35= yypos, yythunkpos35= yythunkpos;  if (!yy_list()) goto l36;  goto l35;
  l36:;	  yypos= yypos35; yythunkpos= yythunkpos35;  if (!yy_atom()) goto l37;  goto l35;
  l37:;	  yypos= yypos35; yythunkpos= yythunkpos35;  if (!yy_eop()) goto l38;  goto l35;
  l38:;	  yypos= yypos35; yythunkpos= yythunkpos35;  if (!yy_ecall()) goto l34;
  }
  l35:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "operand", yybuf+yypos));
  return 1;
  l34:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "operand", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_func_args()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "func_args"));
  {  int yypos40= yypos, yythunkpos40= yythunkpos;  if (!yymatchChar('[')) goto l41;  yyDo(yy_1_func_args, yybegin, yyend);
  l44:;	
  {  int yypos45= yypos, yythunkpos45= yythunkpos;  if (!yy__()) goto l45;  goto l44;
  l45:;	  yypos= yypos45; yythunkpos= yythunkpos45;
  }  if (!yy_identifier()) goto l41;  yyDo(yySet, -1, 0);  yyDo(yy_2_func_args, yybegin, yyend);
  l42:;	
  {  int yypos43= yypos, yythunkpos43= yythunkpos;
  l46:;	
  {  int yypos47= yypos, yythunkpos47= yythunkpos;  if (!yy__()) goto l47;  goto l46;
  l47:;	  yypos= yypos47; yythunkpos= yythunkpos47;
  }  if (!yy_identifier()) goto l43;  yyDo(yySet, -1, 0);  yyDo(yy_2_func_args, yybegin, yyend);  goto l42;
  l43:;	  yypos= yypos43; yythunkpos= yythunkpos43;
  }
  l48:;	
  {  int yypos49= yypos, yythunkpos49= yythunkpos;  if (!yy__()) goto l49;  goto l48;
  l49:;	  yypos= yypos49; yythunkpos= yythunkpos49;
  }  if (!yymatchChar(']')) goto l41;
  l50:;	
  {  int yypos51= yypos, yythunkpos51= yythunkpos;  if (!yy__()) goto l51;  goto l50;
  l51:;	  yypos= yypos51; yythunkpos= yythunkpos51;
  }  yyDo(yy_3_func_args, yybegin, yyend);  goto l40;
  l41:;	  yypos= yypos40; yythunkpos= yythunkpos40;
  {  int yypos52= yypos, yythunkpos52= yythunkpos;  if (!yymatchChar('{')) goto l39;  yypos= yypos52; yythunkpos= yythunkpos52;
  }  yyDo(yy_4_func_args, yybegin, yyend);
  }
  l40:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "func_args", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l39:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "func_args", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_atom()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "atom"));
  {  int yypos54= yypos, yythunkpos54= yythunkpos;  if (!yy_var()) goto l55;  goto l54;
  l55:;	  yypos= yypos54; yythunkpos= yythunkpos54;  if (!yy_string()) goto l56;  goto l54;
  l56:;	  yypos= yypos54; yythunkpos= yythunkpos54;  if (!yy_range()) goto l57;  goto l54;
  l57:;	  yypos= yypos54; yythunkpos= yythunkpos54;  if (!yy_integer()) goto l53;
  }
  l54:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "atom", yybuf+yypos));
  return 1;
  l53:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "atom", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "list"));  if (!yymatchChar('[')) goto l58;
  l59:;	
  {  int yypos60= yypos, yythunkpos60= yythunkpos;  if (!yy__()) goto l60;  goto l59;
  l60:;	  yypos= yypos60; yythunkpos= yythunkpos60;
  }  yyDo(yy_1_list, yybegin, yyend);
  l61:;	
  {  int yypos62= yypos, yythunkpos62= yythunkpos;  if (!yy_expr()) goto l62;  yyDo(yySet, -1, 0);
  l63:;	
  {  int yypos64= yypos, yythunkpos64= yythunkpos;  if (!yy_list_sep()) goto l64;  goto l63;
  l64:;	  yypos= yypos64; yythunkpos= yythunkpos64;
  }  yyDo(yy_2_list, yybegin, yyend);  goto l61;
  l62:;	  yypos= yypos62; yythunkpos= yythunkpos62;
  }  if (!yymatchChar(']')) goto l58;  yyDo(yy_3_list, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "list", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l58:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "list", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_func()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "func"));  if (!yy_func_args()) goto l65;  yyDo(yySet, -2, 0);  if (!yymatchChar('{')) goto l65;
  l66:;	
  {  int yypos67= yypos, yythunkpos67= yythunkpos;
  {  int yypos68= yypos, yythunkpos68= yythunkpos;  if (!yy__()) goto l69;  goto l68;
  l69:;	  yypos= yypos68; yythunkpos= yythunkpos68;  if (!yy___()) goto l67;
  }
  l68:;	  goto l66;
  l67:;	  yypos= yypos67; yythunkpos= yythunkpos67;
  }  yyDo(yy_1_func, yybegin, yyend);  if (!yy_lexpr()) goto l65;  yyDo(yySet, -1, 0);  yyDo(yy_2_func, yybegin, yyend);
  l70:;	
  {  int yypos71= yypos, yythunkpos71= yythunkpos;  if (!yy_lexpr()) goto l71;  yyDo(yySet, -1, 0);  yyDo(yy_2_func, yybegin, yyend);  goto l70;
  l71:;	  yypos= yypos71; yythunkpos= yythunkpos71;
  }
  l72:;	
  {  int yypos73= yypos, yythunkpos73= yythunkpos;  if (!yy__()) goto l73;  goto l72;
  l73:;	  yypos= yypos73; yythunkpos= yythunkpos73;
  }  if (!yymatchChar('}')) goto l65;  yyDo(yy_3_func, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "func", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l65:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "func", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eop()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eop"));  if (!yymatchChar('(')) goto l74;  if (!yy_op()) goto l74;  if (!yymatchChar(')')) goto l74;
  yyprintf((stderr, "  ok   %s @ %s\n", "eop", yybuf+yypos));
  return 1;
  l74:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eop", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_op()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "op"));  if (!yy_operand()) goto l75;  yyDo(yySet, -3, 0);  if (!yy__()) goto l75;
  l76:;	
  {  int yypos77= yypos, yythunkpos77= yythunkpos;  if (!yy__()) goto l77;  goto l76;
  l77:;	  yypos= yypos77; yythunkpos= yythunkpos77;
  }  if (!yy_symbol()) goto l75;  yyDo(yySet, -2, 0);  if (!yy__()) goto l75;
  l78:;	
  {  int yypos79= yypos, yythunkpos79= yythunkpos;  if (!yy__()) goto l79;  goto l78;
  l79:;	  yypos= yypos79; yythunkpos= yythunkpos79;
  }  if (!yy_operand()) goto l75;  yyDo(yySet, -1, 0);  yyDo(yy_1_op, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "op", yybuf+yypos));  yyDo(yyPop, 3, 0);
  return 1;
  l75:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "op", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_ecall()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "ecall"));  if (!yymatchChar('(')) goto l80;  if (!yy_identifier()) goto l80;  yyDo(yySet, -2, 0);  yyDo(yy_1_ecall, yybegin, yyend);
  l81:;	
  {  int yypos82= yypos, yythunkpos82= yythunkpos;  if (!yy_arg_sep()) goto l82;  if (!yy_expr()) goto l82;  yyDo(yySet, -1, 0);  yyDo(yy_2_ecall, yybegin, yyend);  goto l81;
  l82:;	  yypos= yypos82; yythunkpos= yythunkpos82;
  }  if (!yymatchChar(')')) goto l80;  yyDo(yy_3_ecall, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "ecall", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l80:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ecall", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_arg_sep()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "arg_sep"));
  {  int yypos84= yypos, yythunkpos84= yythunkpos;  if (!yymatchChar(',')) goto l85;
  l86:;	
  {  int yypos87= yypos, yythunkpos87= yythunkpos;
  {  int yypos88= yypos, yythunkpos88= yythunkpos;  if (!yy__()) goto l89;  goto l88;
  l89:;	  yypos= yypos88; yythunkpos= yythunkpos88;  if (!yy___()) goto l87;
  }
  l88:;	  goto l86;
  l87:;	  yypos= yypos87; yythunkpos= yythunkpos87;
  }  goto l84;
  l85:;	  yypos= yypos84; yythunkpos= yythunkpos84;  if (!yy__()) goto l83;
  l90:;	
  {  int yypos91= yypos, yythunkpos91= yythunkpos;  if (!yy__()) goto l91;  goto l90;
  l91:;	  yypos= yypos91; yythunkpos= yythunkpos91;
  }
  }
  l84:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "arg_sep", yybuf+yypos));
  return 1;
  l83:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "arg_sep", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_symbol()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "symbol"));
  {  int yypos93= yypos, yythunkpos93= yythunkpos;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l94;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\320\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l94;
  l95:;	
  {  int yypos96= yypos, yythunkpos96= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\320\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l96;  goto l95;
  l96:;	  yypos= yypos96; yythunkpos= yythunkpos96;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l94;  yyDo(yy_1_symbol, yybegin, yyend);  goto l93;
  l94:;	  yypos= yypos93; yythunkpos= yythunkpos93;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l92;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\360\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l92;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\360\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l92;
  l97:;	
  {  int yypos98= yypos, yythunkpos98= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\162\374\000\360\001\000\000\300\001\000\000\120\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l98;  goto l97;
  l98:;	  yypos= yypos98; yythunkpos= yythunkpos98;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l92;  yyDo(yy_2_symbol, yybegin, yyend);
  }
  l93:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "symbol", yybuf+yypos));
  return 1;
  l92:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "symbol", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_identifier()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "identifier"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l99;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l99;
  l100:;	
  {  int yypos101= yypos, yythunkpos101= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\040\377\003\000\000\000\000\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l101;  goto l100;
  l101:;	  yypos= yypos101; yythunkpos= yythunkpos101;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l99;  yyDo(yy_1_identifier, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "identifier", yybuf+yypos));
  return 1;
  l99:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "identifier", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy___()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "__"));
  {  int yypos103= yypos, yythunkpos103= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l103;  goto l104;
  l103:;	  yypos= yypos103; yythunkpos= yythunkpos103;
  }
  l104:;	  if (!yymatchClass((unsigned char *)"\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l102;
  yyprintf((stderr, "  ok   %s @ %s\n", "__", yybuf+yypos));
  return 1;
  l102:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "__", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_expr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "expr"));
  {  int yypos106= yypos, yythunkpos106= yythunkpos;  if (!yy_op()) goto l107;  goto l106;
  l107:;	  yypos= yypos106; yythunkpos= yythunkpos106;  if (!yy_eop()) goto l108;  goto l106;
  l108:;	  yypos= yypos106; yythunkpos= yythunkpos106;  if (!yy_ecall()) goto l109;  goto l106;
  l109:;	  yypos= yypos106; yythunkpos= yythunkpos106;  if (!yy_func()) goto l110;  goto l106;
  l110:;	  yypos= yypos106; yythunkpos= yythunkpos106;  if (!yy_list()) goto l111;  goto l106;
  l111:;	  yypos= yypos106; yythunkpos= yythunkpos106;  if (!yy_atom()) goto l105;
  }
  l106:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "expr", yybuf+yypos));
  return 1;
  l105:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "expr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_assign()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "assign"));
  {  int yypos113= yypos, yythunkpos113= yythunkpos;  if (!yy_identifier()) goto l114;  yyDo(yySet, -2, 0);  goto l113;
  l114:;	  yypos= yypos113; yythunkpos= yythunkpos113;  if (!yy_symbol()) goto l112;  yyDo(yySet, -2, 0);
  }
  l113:;	  if (!yy__()) goto l112;
  l115:;	
  {  int yypos116= yypos, yythunkpos116= yythunkpos;  if (!yy__()) goto l116;  goto l115;
  l116:;	  yypos= yypos116; yythunkpos= yythunkpos116;
  }  if (!yymatchChar('=')) goto l112;  if (!yy__()) goto l112;
  l117:;	
  {  int yypos118= yypos, yythunkpos118= yythunkpos;  if (!yy__()) goto l118;  goto l117;
  l118:;	  yypos= yypos118; yythunkpos= yythunkpos118;
  }
  {  int yypos119= yypos, yythunkpos119= yythunkpos;  if (!yy_icall()) goto l120;  yyDo(yySet, -1, 0);  goto l119;
  l120:;	  yypos= yypos119; yythunkpos= yythunkpos119;  if (!yy_expr()) goto l112;  yyDo(yySet, -1, 0);
  }
  l119:;	  yyDo(yy_1_assign, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "assign", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l112:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "assign", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_icall()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "icall"));  if (!yy_identifier()) goto l121;  yyDo(yySet, -2, 0);  yyDo(yy_1_icall, yybegin, yyend);  if (!yy_arg_sep()) goto l121;  if (!yy_expr()) goto l121;  yyDo(yySet, -1, 0);  yyDo(yy_2_icall, yybegin, yyend);
  l122:;	
  {  int yypos123= yypos, yythunkpos123= yythunkpos;  if (!yy_arg_sep()) goto l123;  if (!yy_expr()) goto l123;  yyDo(yySet, -1, 0);  yyDo(yy_2_icall, yybegin, yyend);  goto l122;
  l123:;	  yypos= yypos123; yythunkpos= yythunkpos123;
  }  yyDo(yy_3_icall, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "icall", yybuf+yypos));  yyDo(yyPop, 2, 0);
  return 1;
  l121:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "icall", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_comment()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "comment"));
  l125:;	
  {  int yypos126= yypos, yythunkpos126= yythunkpos;  if (!yy__()) goto l126;  goto l125;
  l126:;	  yypos= yypos126; yythunkpos= yythunkpos126;
  }  if (!yymatchChar('#')) goto l124;
  l127:;	
  {  int yypos128= yypos, yythunkpos128= yythunkpos;  if (!yymatchClass((unsigned char *)"\377\333\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l128;  goto l127;
  l128:;	  yypos= yypos128; yythunkpos= yythunkpos128;
  }
  {  int yypos129= yypos, yythunkpos129= yythunkpos;  if (!yy___()) goto l129;  goto l130;
  l129:;	  yypos= yypos129; yythunkpos= yythunkpos129;
  }
  l130:;	  yyDo(yy_1_comment, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "comment", yybuf+yypos));
  return 1;
  l124:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "comment", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_empty_line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "empty_line"));
  l132:;	
  {  int yypos133= yypos, yythunkpos133= yythunkpos;  if (!yy__()) goto l133;  goto l132;
  l133:;	  yypos= yypos133; yythunkpos= yythunkpos133;
  }  if (!yy___()) goto l131;  yyDo(yy_1_empty_line, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "empty_line", yybuf+yypos));
  return 1;
  l131:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "empty_line", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy__()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "_"));  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l134;
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yybuf+yypos));
  return 1;
  l134:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "_", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bad()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bad"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l135;  if (!yymatchDot()) goto l135;
  l136:;	
  {  int yypos137= yypos, yythunkpos137= yythunkpos;  if (!yymatchDot()) goto l137;  goto l136;
  l137:;	  yypos= yypos137; yythunkpos= yythunkpos137;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l135;  yyDo(yy_1_bad, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bad", yybuf+yypos));
  return 1;
  l135:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bad", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eof()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eof"));
  {  int yypos139= yypos, yythunkpos139= yythunkpos;  if (!yymatchDot()) goto l139;  goto l138;
  l139:;	  yypos= yypos139; yythunkpos= yythunkpos139;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "eof", yybuf+yypos));
  return 1;
  l138:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eof", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_lexpr()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "lexpr"));
  l141:;	
  {  int yypos142= yypos, yythunkpos142= yythunkpos;  if (!yy__()) goto l142;  goto l141;
  l142:;	  yypos= yypos142; yythunkpos= yythunkpos142;
  }
  {  int yypos143= yypos, yythunkpos143= yythunkpos;  if (!yy_empty_line()) goto l144;  goto l143;
  l144:;	  yypos= yypos143; yythunkpos= yythunkpos143;  if (!yy_comment()) goto l145;  goto l143;
  l145:;	  yypos= yypos143; yythunkpos= yythunkpos143;  if (!yy_icall()) goto l146;  goto l143;
  l146:;	  yypos= yypos143; yythunkpos= yythunkpos143;  if (!yy_assign()) goto l147;  goto l143;
  l147:;	  yypos= yypos143; yythunkpos= yythunkpos143;  if (!yy_expr()) goto l140;
  }
  l143:;	
  l148:;	
  {  int yypos149= yypos, yythunkpos149= yythunkpos;  if (!yy__()) goto l149;  goto l148;
  l149:;	  yypos= yypos149; yythunkpos= yythunkpos149;
  }
  {  int yypos150= yypos, yythunkpos150= yythunkpos;  if (!yy___()) goto l150;  goto l151;
  l150:;	  yypos= yypos150; yythunkpos= yythunkpos150;
  }
  l151:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "lexpr", yybuf+yypos));
  return 1;
  l140:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "lexpr", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_body()
{  int yypos0= yypos, yythunkpos0= yythunkpos;  yyDo(yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "body"));
  {  int yypos153= yypos, yythunkpos153= yythunkpos;  if (!yy_lexpr()) goto l154;  yyDo(yySet, -1, 0);  yyDo(yy_1_body, yybegin, yyend);
  l155:;	
  {  int yypos156= yypos, yythunkpos156= yythunkpos;  if (!yy_lexpr()) goto l156;  yyDo(yySet, -1, 0);  yyDo(yy_1_body, yybegin, yyend);  goto l155;
  l156:;	  yypos= yypos156; yythunkpos= yythunkpos156;
  }  if (!yy_eof()) goto l154;  goto l153;
  l154:;	  yypos= yypos153; yythunkpos= yythunkpos153;
  l157:;	
  {  int yypos158= yypos, yythunkpos158= yythunkpos;  if (!yy_lexpr()) goto l158;  goto l157;
  l158:;	  yypos= yypos158; yythunkpos= yythunkpos158;
  }  if (!yy_bad()) goto l152;  if (!yy_eof()) goto l152;
  }
  l153:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "body", yybuf+yypos));  yyDo(yyPop, 1, 0);
  return 1;
  l152:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "body", yybuf+yypos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= malloc(yybuflen);
      yytextlen= 1024;
      yytext= malloc(yytextlen);
      yythunkslen= 32;
      yythunks= malloc(sizeof(yythunk) * yythunkslen);
      yyvalslen= 32;
      yyvals= malloc(sizeof(YYSTYPE) * yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_body);
}

#endif


/* borrowed from O'Reilly book "lex & yacc" pg. 157 */
char *yy_input_ptr;
int yy_input_len;

node* rb_str_new(char * text, int length) {
  printf("noop\n");
  return (node*)malloc(sizeof(node));
}

node* rb_ary_new() {
  printf("noop\n");
  return (node*)malloc(sizeof(node));
}

void stack_push() {
  if(++stackp == STACK_LEN) exit(1);
  stack_argc[stackp] = 0;
}

void stack_add(node* n) {
  argp = 0;
  stack[stackp][stack_argc[stackp]++] = n;
}

node* stack_pop() {
  node** args = malloc(sizeof(node*) * stack_argc[stackp]);
  for(i=0; i<stack_argc[stackp]; i++) args[i] = stack[stackp][i];
  stackp--;
  return args;
}

char* yytos(char* yytext, int yyleng) {
  char* s = malloc(sizeof(char) * (yyleng + 1));
  strcpy(s, "");
  strncat(s, yytext, yyleng);
  return s;
}

node* create_int_node(char* yytext, int yyleng) {
  node* n = malloc(sizeof(node));
  n->type = INT_TYPE;
  n->value.i = atoi(yytext);
  return n;
}

node* create_str_node(char* yytext, int yyleng) {
  node* n = malloc(sizeof(node));
  n->type = STR_TYPE;
  n->value.s = malloc(sizeof(char) * (yyleng + 1));
  strcpy(n->value.s, "");
  strncat(n->value.s, yytext, yyleng);
  return n;
}

node* create_rng_node(node* first, node* last) {
  node* n = malloc(sizeof(node));
  n->type = RNG_TYPE;
  n->value.r = malloc(sizeof(struct range));
  n->value.r->first = first;
  n->value.r->last = last;
  return n;
}

node* create_var_node(char* name) {
  node* n = malloc(sizeof(node));
  n->type = VAR_TYPE;
  n->value.v = malloc(sizeof(struct var));
  n->value.v->name = name;
  return n;
}

node* create_call_node(char* name, int argc, node** args) {
  printf("argc=%d\n", argc);
  node* n = malloc(sizeof(node));
  n->type = CALL_TYPE;
  n->value.c = malloc(sizeof(struct call));
  n->value.c->name = name;
  n->value.c->argc = argc;
  n->value.c->args = args;
  return n;
}

node* create_err_node(char* yytext, int yyleng) {
  node* n = malloc(sizeof(node));
  n->type = ERR_TYPE;
  n->value.e = malloc(sizeof(char) * (yyleng + 1));
  strcpy(n->value.e, "");
  strncat(n->value.e, yytext, yyleng);
  return n;
}

int yy_input(char *buf, int max_size) {
  int len = strlen(yy_input_ptr);
  int n = max_size < len ? max_size : len;
  if(n > 0) {
    memcpy(buf, yy_input_ptr, n);
    yy_input_ptr += n;
  }
  return n;
}

GSList* airball_parse(char *source) {
  parse_ast = NULL;
  yy_input_ptr = source;
  yy_input_len = strlen(yy_input_ptr);
  while (yyparse());
  return parse_ast;
}

